### ISSUE TITLE
Why not  import the build package?

### ISSUE THREAD

**Issue by gernest** [magefile/mage#1]
I was going through the code and noticed there was copies of files found in the build package https://golang.org/pkg/go/build/ 

Any reason why not just to import it? I am thinking about long term maintenance implications !

**Comment by gernest** [comment]
Probably to add mage build target `//+build mage`

**Comment by natefinch** [comment]
Hi, Just to clarify here. I had to hack the stdlib go/build package to add functionality for "required" tags.  The way tags work with go is that each file can opt out of being considered for a build by specifying build tags.  But there's no way to say "only build code that has tag x".  specifying tag x means you build files with no tags *and* those with that tag.  And so I had to fork and hack the package.
