### ISSUE TITLE
Verbose output shown in init function

### ISSUE THREAD

**Issue by pauldotknopf** [magefile/mage#102]
```golang
func init() {
	if exe := os.Getenv("GOEXE"); exe != "" {
		goexe = exe
	}

	// Update the GOARCH.
	if output, err := sh.Output(goexe, "env", "GOARCH"); err == nil {
		goarch = output
	} else {
		panic(fmt.Sprintf("couldn't get GOARCH: %v", err))
	}
}
```

```
> mage
2018/01/26 21:55:25 exec: go env GOARCH
```

I expected that output only when invoking ```mage -v```.

When the actual targets get run, the ```sh``` commands are properly muted.

**Comment by natefinch** [comment]
Ahh yeah, this is a tricky one.  -v is evaluated in the main function.  It could be evaluated in an init function, but even then, the order on init functions is not defined in the spec. I believe they get run in file-lexicographic order (i.e. the init in a.go before the init in b.go), but that's not in the spec and therefore subject to change, or subject to working differently with different compilers.

A solution for right now would be to make this a dependency for the targets that need it.  If there aren't too many that need goarch and goexe, that's not too bad.

I'll look into making the -v handling different, but I think if you're running stuff in an init, you're really not guaranteed to have anything run before it.  Definitely it'll run before func main, which is where a lot of the logic goes in mage.

**Comment by natefinch** [comment]
I'm going to close this as won't fix for now. I generally advise againt init functions anyway.
