### ISSUE TITLE
Logging wrappers?

### ISSUE THREAD

**Issue by wrouesnel** [magefile/mage#106]
What's the normally intended use of stdout/stderr in mage files for user functions? I notice mage has no logging wrappers for adding build specific information, so I'm not super clear on the design intent here?

**Comment by natefinch** [comment]
I'm not entirely sure what you're asking for.  os.Stderr and os.Stdout exist in a running mage target just as they would in any other go executable.  I'm not sure what build-specific info you're looking for...

**Comment by natefinch** [comment]
The intent is that if you want just simple output controlled by the verbose
flag, you can use the standard log package.

It's just the standard log package, so you can tweak the output how ever
you want, through the normal log package functions.  So you can change
where it writes to, what information it prepends, etc.

**Comment by natefinch** [comment]
Closing for now, assuming your question is answered, feel free to reopen if not.
