### ISSUE TITLE
Add link to the magefile site in the project description

### ISSUE THREAD

**Issue by nerro** [magefile/mage#109]
### Description
It's really small improvement but I think it's a good one.

Many projects have links to their web sites in the project's description (e.g. https://github.com/golang/go or https://github.com/golang/dep) so people don't need to scroll down and search for the link (usually the web site contains more info as readme file).

### Proposal:
Add link to https://magefile.org/ in the project description.

That's all :wink:.

**Comment by natefinch** [comment]
Done, thanks for pinging me about it :)
