### ISSUE TITLE
-v should print out dependencies that are run

### ISSUE THREAD

**Issue by natefinch** [magefile/mage#110]
if you have 
```go
func Foo() {
    mg.Deps(Bar, Baz)
}
```
and you run `mage -v foo` currently we print out 
```
Running Foo
```

But it would be nice if it said
```
Running Bar
Running Baz
Running Foo
```

**Comment by dotpy3** [comment]
I've started to tackle this issue with this commit: https://github.com/dotpy3/mage/commit/a5c6c959a56a6d55cc068eba01da6566c6c1b6df

Here's what it outputs:
```
$ mage -v buildWithDeps
Running target: BuildWithDeps
Running dependency: Build
```

Any thoughts about this? I'd especially appreciate input on the logger creation/usage. If that's all good, I'll submit a pull request!

**Comment by natefinch** [comment]
I'll take a look tonight. Thanks for the help!

**Comment by dotpy3** [comment]
@natefinch Any news about this? :)

**Comment by natefinch** [comment]
Sorry I'll get it merged in tonight :)
