### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by mcandre** [magefile/mage#113]
Mage is so amazing, a breath of fresh air for build tools! Love the minimalism and potential for highly cross-platform builds! Hey, could we get some tab completion for target names? Perhaps a bash completion script?

**Comment by natefinch** [comment]
That's a great idea. I'll have to look into it.  PRs welcome ;)

**Comment by natefinch** [comment]
I saw some other tool (I forget which now) that would spit out the right scripts from a command (for either bash or zsh).  That seems like a good way to do it.

**Comment by Hanzei** [comment]
https://github.com/posener/complete could help

**Comment by natefinch** [comment]
So..... I think for now I'm going to close this, because I worry it's going to be a maintenance headache for little real gain.  We can post completion scripts on the wiki or the website, and not have to worry about having our code do exactly the right thing.

**Comment by yohanyflores** [comment]
I am not a developer Bash, however this works for me:

mage-completion.sh:
```
#/usr/bin/env bash

_mage_completions()
{
    local cur prev opts

    # namespaces with colon
    _get_comp_words_by_ref -n : cur

    # prev word.
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # maybe  parse mage -h is better for support future commands??
    opts="-clean -compile -init -l -h -version -debug -h -f -keep -gocmd -t -v"

    case "${prev}" in
        -compile)
            COMPREPLY+=( $(compgen -f ${cur}) )
            ;;
        -d)
            COMPREPLY+=( $(compgen -f ${cur}) )
            ;;
        -gocmd)
            COMPREPLY+=( $(compgen -f ${cur}) )
            ;;
        -t)
            opts="30s 1m 1m30s 5m30s 10m 30m"
            COMPREPLY+=( $(compgen -W "${opts}" -- ${cur}) )
            ;;
        *)
            if [[ ${cur} == -* ]]; then
                COMPREPLY+=( $(compgen -W "${opts}" -- ${cur}) )
            else
                COMPREPLY+=( $(compgen -W "$(mage -l | awk '{print tolower($1)}' | grep -v "targets:")" -- "${cur}"))
            fi
            ;;
    esac

    __ltrim_colon_completions "$cur"
}

complete -F _mage_completions mage
```

I'm using it this way:

```
source mage-completion.sh
```

**Comment by mcandre** [comment]
You sir win one free Internet!

Could we publish this to Homebrew to make it more accessible :)

**Comment by yohanyflores** [comment]
Sure :)

**Comment by iwittkau** [comment]
I created [a mage CLI frontend](https://github.com/iwittkau/mage-select) to circumvent bash completion. Maybe someone else finds this useful.

**Comment by natefinch** [comment]
Dude, that is freakin' cool!

**Comment by hbt** [comment]
zsh version reusing the bash version. If you have one with the custom bash functions implemented in pure zsh; feel free to share.

```
autoload -U compinit
autoload -U bashcompinit
compinit
bashcompinit
_get_comp_words_by_ref () {
}
__ltrim_colon_completions() {
}

# https://github.com/magefile/mage/issues/113#issuecomment-437710124
#source the_bash_version
```



Also, this (https://github.com/urfave/cli/blob/master/docs/v2/manual.md#bash-completion) is a good implementation of general bash/zsh autocompletion for cli tools. 


The completion scripts (https://github.com/urfave/cli/tree/61026898ff6cbe7c1b4f19feafc6f9ffe098d7e2/autocomplete) are simple and all the logic is go and works across interpreters.

**Comment by sluedecke** [comment]
Thanks a lot for https://github.com/magefile/mage/issues/113#issuecomment-437710124 !

Since one can force colored by setting `MAGEFILE_ENABLE_COLOR=1` or setting it within the magefile like this:

```
func init() {
	// enable colored output from mage if not set from the outside
	if os.Getenv(mg.EnableColorEnv) == "" {
		os.Setenv(mg.EnableColorEnv, "1")
	}
}
```

the completion script can be adjusted accordingly with:

```
#!/usr/bin/env bash

_mage_completions()
{
    local cur prev opts

    # namespaces with colon
    _get_comp_words_by_ref -n : cur

    # prev word.
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    case "${prev}" in
        -compile)
            COMPREPLY+=( $(compgen -f -- "${cur}") )
            ;;
        -d)
            COMPREPLY+=( $(compgen -d -- "${cur}") )
            ;;
        -gocmd)
            COMPREPLY+=( $(compgen -f -- "${cur}") )
            ;;
        -t)
            opts="30s 1m 1m30s 2m 2m30s 3m 3m30s 4m 4m30s 5m 10m 20m 30m 1h"
            COMPREPLY+=( $(compgen -W "${opts}" -- ${cur}) )
            ;;
        *)
            
            if [[ ${cur} == -* ]]; then
                opts="$(MAGEFILE_ENABLE_COLOR=0 mage -h | grep "^\\s*-" | awk '{print $1}')"
            else
                opts="$(MAGEFILE_ENABLE_COLOR=0 mage -l | tail -n +2 | awk '{print tolower($1)}')"
            fi
            COMPREPLY+=( $(compgen -W "${opts}" -- "${cur}"))
            ;;
    esac

    __ltrim_colon_completions "$cur"
}

complete -F _mage_completions mage
```

**Comment by mcandre** [comment]
Update:

Fixed handling default tasks.

```zsh
# mage
_mage() {
    local tasks=( ${(f)"$(mage -l | grep -v 'Targets:' | grep -v 'default target' | grep -v '^$' | awk '{ print $1 }' | sed 's/\*$//')"} )
    _arguments -C '1:task:('"${tasks[*]}"')'
}
compdef _mage mage
```

Using separate awk _and_ sed subprocesses is ugly. Further improvements welcome.

**Comment by mcandre** [comment]
Sounds good.

I thought that mage already aggressively cached resources. The only time `mage -l` should be slow, is when running it on several fresh git clones in a row.
