### ISSUE TITLE
Add option to change working directory

### ISSUE THREAD

**Issue by dradtke** [magefile/mage#118]
It would be nice to be able to specify a directory to cd into before running the requested target.

Say you have a few packages that contain their own Magefile, because their targets contain package-specific functionality that you don't want in your root Magefile, e.g.

```
pkg/
  a/
    Magefile.go
  b/
    Magefile.go
```

From the `pkg` directory, it would be nice to be able to run the targets by doing:

```sh
$ mage -d a <target>  # run mage within a
$ mage -d b <target>  # run mage within b
```

This would be equivalent to e.g. `cd a && mage <target>`, but without requiring the shell, which makes it more cross-platform and friendly to `go generate`.

**Comment by natefinch** [comment]
This is a good idea, and definitely should be doable fairly easily.

**Comment by natefinch** [comment]
done in #159!
