### ISSUE TITLE
It is difficult to get make-like behaviour with target.Path

### ISSUE THREAD

**Issue by bdalton** [magefile/mage#122]
There are two cases in make where a rule is executed:
1. the target does not exist.
2. the target is older than one of the sources.

target.Path(dst, sources...) returns true, nil on (2), but returns false, err on (1).
That leads me to think that maybe I could do something like this:

```
outOfDate, err := target.Path(dst, source1, source2)
if err != nil && !os.IsNotExist(err) {
   return err
}
if outOfDate || os.IsNotExist(err) {
   ... action ...
}
```

Unfortunately, if any of the sources doesn't exist, I will also get an os.IsNotExist() also returning true so I can't distinguish between the target not existing and one of the sources existing.

**Comment by bdalton** [comment]
Sure, I'll submit a PR later today

**Comment by bdalton** [comment]
PR submitted

**Comment by natefinch** [comment]
Thank you!

**Comment by natefinch** [comment]
fixed by 131.  If there's a different behavior you'd like, we can add it to another function, perhaps.
