### ISSUE TITLE
Build target uniqueness constraint

### ISSUE THREAD

**Issue by faxal** [magefile/mage#136]
Currently all build targets must be unique regardless of namespace. This kind of limits the use of namespaces.

For example something like below is not possible:

`init:instance`
`build:instance`

I actually wanted to make this work such that following is possible. This requires #135 

`build:instance inst1`

**Comment by natefinch** [comment]
Oops, yeah.  That's definitely a bug.  The whole point of namespaces is to
allow two namespaces to have the same target name.
