### ISSUE TITLE
Mage fails to locate transient dependencies saved via Go modules

### ISSUE THREAD

**Issue by dradtke** [magefile/mage#140]
It looks like Mage doesn't fully support dependencies defined by Go modules. In particular, transient dependencies fail because they're not placed in the place that Mage expects.

To reproduce, create a new project containing a dependency, followed by a Magefile that uses it:

```
$ go mod init app
$ go get golang.org/x/text/unicode/norm
```

```go
// +build mage

package main

import (
        "golang.org/x/text/unicode/norm"
)

func Test() {
        print("unicode version: " + norm.Version)
}
```

Running `mage test` fails with the following error:

```
Error: failed to check types in directory: magefile.go:6:2: could not import golang.org/x/text/unicode/norm (type-checking package "golang.org/x/text/unicode/norm" failed (/home/damien/go/pkg/mod/golang.org/x/text@v0.3.0/unicode/norm/normalize.go:15:2: could not import golang.org/x/text/transform (cannot find package "golang.org/x/text/transform" in any of:
        /usr/local/go/src/golang.org/x/text/transform (from $GOROOT)
        /home/damien/go/src/golang.org/x/text/transform (from $GOPATH))))
```

This is because `golang.org/x/text/unicode/norm` depends on `golang.org/x/text/transform`, which exists, but not in the GOPATH. Using modules, Go downloads both dependencies to `~/go/pkg/mod/golang.org/x/text@v0.3.0/`.

Mage should be updated to include the logic utilized by e.g. `go list -m -f '{{.Dir}}' all` to locate modularized dependencies, if being compiled with Go 1.11 or later.

**Comment by natefinch** [comment]
I'm looking at this now, thanks for letting me know.

**Comment by dradtke** [comment]
I just noticed https://github.com/magefile/mage/issues/124, so maybe Mage works with 1.11 in general and only fails with these transitive dependencies.

**Comment by natefinch** [comment]
Russ fixed the fact that they had broken people who relied on parsing source but it sounds like there's a more subtle bug that is likely my fault.  I'll look into it.

**Comment by natefinch** [comment]
Oh... make sure you use mage built with go 1.11.  te 2.2.0 release is that, or of course you can build it yourself.  Note that if you use mage's `mage install` target, it will build itself with your default go installation.

**Comment by dradtke** [comment]
I can confirm that this is still an issue with the 2.2.0 release, as well as Mage built from source using Go 1.11.

**Comment by natefinch** [comment]
Hmm I'll retry the check on my end. I was getting a go build error for some reason, not a mage error. 

Is your default 'go' version  1.11?

**Comment by dradtke** [comment]
Yeah, `go version` prints out:

```
go version go1.11 linux/amd64
```

**Comment by natefinch** [comment]
can you update to master and run with -debug and post the results here?  That may help me figure some stuff out. Thanks!

**Comment by dradtke** [comment]
Output of `mage --version`:

```
Mage Build Tool v2.2.0-5-g01342b9
Build Date: 2018-08-31T09:58:42-05:00
Commit: 01342b9
```

Output of `mage -debug test`:

```
DEBUG: found magefiles: magefile.go
DEBUG: output exe is  /home/damien/.magefile/63673f36d73816925861f352c4f85317c6f309a2
DEBUG: no existing exe, creating new
Error parsing magefiles: failed to check types in directory: magefile.go:6:2: could not import golang.org/x/text/unicode/norm (type-checking package "golang.org/x/text/unicode/norm" failed (/home/damien/go/pkg/mod/golang.org/x/text@v0.3.0/unicode/norm/normalize.go:15:2: could not import golang.org/x/text/transform (cannot find package "golang.org/x/text/transform" in any of:
        /usr/local/go/src/golang.org/x/text/transform (from $GOROOT)
        /home/damien/go/src/golang.org/x/text/transform (from $GOPATH))))
```

Doesn't look like it added a whole lot of new info, but I can confirm that it attempts to recreate the exe every time I run it.

**Comment by natefinch** [comment]
Oh, hmm, yeah, I'll need to put.more debugging in the file parsing
library... I'll do thay today when I get a chance.

**Comment by natefinch** [comment]
ok, I think I have a fix... I didn't realize they had added a bunch of rigamarole in the go/build package in 1.11 to support code outside gopath.  Can you check out the build-1.11 branch and try that?  I'm hopeful that will work, since it's the same code as is in 1.11 itself.

**Comment by natefinch** [comment]
I just tested this on my machine outside gopath and it worked perfectly, aside from being a bit slow the first time it downloads the dependency.

**Comment by natefinch** [comment]
closing this as fixed, but if you have problems, feel free to reopen

**Comment by dradtke** [comment]
So I think this works when I test it on Mac, but I'm still having trouble on Linux (specifically, openSUSE 42.3). What platform do you generally develop on?

**Comment by dradtke** [comment]
I just reproduced it on a Debian Stretch server as well. Can you see if you can reproduce the issue on Linux?

**Comment by natefinch** [comment]
I'll give it a try. I only tested on a Mac, but I can't imagine the
platform matters.  There's probably something else at play.... But I can
verify on Linux easily enough.

What are you seeing on Debian?

**Comment by dradtke** [comment]
It's the same error that I originally reported. I'll let you know if I can get some additional detail.

**Comment by dradtke** [comment]
So I think I was able to reproduce this on Mac, and I don't think it's actually an issue with Mage, but with the `go/types` package.

To reproduce, I ensured a clean GOPATH (this is crucial):

```bash
$ rm -rf ${GOPATH}/pkg
$ rm -rf ${GOPATH}/src/golang.org/x/text
```

Then I typechecked a module-enabled package that uses `golang.org/x/text/unicode/norm` (go.mod will contain a dependency on `golang.org/x/text v0.3.0`) using this script:

```go
package main

import (
        "fmt"
        "go/ast"
        "go/importer"
        "go/parser"
        "go/token"
        "go/types"
)

func main() {
        cfg := types.Config{
                Importer: importer.For("source", nil),
        }
        fset := token.NewFileSet()
        f, err := parser.ParseFile(fset, "app/app.go", nil, 0)
        if err != nil {
                panic(err)
        }
        pkg, err := cfg.Check("app", fset, []*ast.File{f}, nil)
        if err != nil {
                panic(err)
        }
        fmt.Println("successfully parsed package: " + pkg.Name())
}
```

Building the package with `go build` works fine, but running this script on it results in an error:

```
could not import golang.org/x/text/unicode/norm (type-checking package "golang.org/x/text/unicode/norm" failed (/Users/dradtke/Workspace/go/pkg/mod/golang.org/x/text@v0.3.0/unicode/norm/normalize.go:15:2: could not import golang.org/x/text/transform (cannot find package "golang.org/x/text/transform" in any of:
        /usr/local/Cellar/go/1.11/libexec/src/golang.org/x/text/transform (from $GOROOT)
        /Users/dradtke/Workspace/go/src/golang.org/x/text/transform (from $GOPATH))))
```

My guess is that maybe it needs a custom importer, but I don't know what exactly that would look like yet.

**Comment by dradtke** [comment]
I submitted a new issue to Go, since I was able to reliably reproduce this without Mage: https://github.com/golang/go/issues/27556. My guess is that either a new importer will need to be used, or a different package from `go/types` such as [packages](https://godoc.org/golang.org/x/tools/go/packages).

**Comment by natefinch** [comment]
I can switch to x/packages. We'll see how that goes.  What's weird is that
it works fine most of the time. Maybe because I haven't deleted my pkg
directory.

**Comment by dradtke** [comment]
I started giving it a shot here. I got the tests in `parse` to pass, but that's about as far as I've gotten so far: https://github.com/magefile/mage/compare/master...dradtke:go-packages
