### ISSUE TITLE
Exclamation marks "!" don't delimit the short description in `mage -l`

### ISSUE THREAD

**Issue by jlucktay** [magefile/mage#142]
I have a small `magefile.go`:

    // +build mage
    
    package main
    
    import "fmt"
    
    // Builds some things! A second sentence.
    func Build() {}
    
    // This is a demo.
    func Demo() {
    	fmt.Println("Hello world!")
    }

The comment on `func Build()` doesn't get delimited properly when I do `mage -l`:

    $ mage -l
    Targets:
      build    Builds some things! A second sentence.
      demo     This is a demo.

I would expect `mage -l` to look like this:

    $ mage -l
    Targets:
      build    Builds some things!
      demo     This is a demo.

Have had a very quick look at the code to try and find the delimiter logic, but didn't turn up anything.

**Comment by natefinch** [comment]
Mage uses the godoc code to get the first sentence.... Maybe they don't
delimit on an exclamation point either? I'll have to look at it.

**Comment by jlucktay** [comment]
Had some more time to search; looks like [this is it](https://github.com/golang/go/blob/master/src/go/doc/synopsis.go).

The logic described in the comment there is that the _"sentence ends after the first period followed by space and not preceded by exactly one uppercase letter"_.

**Comment by natefinch** [comment]
Thanks.  It's not a perfect heuristic, but I don't think anything could be perfect, and I would rather use the one that go doc uses that try to make my own (especially looking at that code).
