### ISSUE TITLE
unknown import path "github.com/magefile/mage/types": cannot find module providing package on go 1.11.0

### ISSUE THREAD

**Issue by nullstyle** [magefile/mage#147]
# Steps to recreate

Install go 1.11.0 then:

1. create a new dir, cd into it
2. `go mod init app`
3. `mage -init`
4. `mage build`

# Error output

```
go: finding github.com/magefile/mage/types latest
../../../go/pkg/mod/github.com/magefile/mage@v2.2.0+incompatible/mg/deps.go:13:2: unknown import path "github.com/magefile/mage/types": cannot find module providing package github.com/magefile/mage/types
Error: error compiling magefiles
```

# Other notes

When trying to update the mage module from within this test dir:

```
$ go get -u github.com/magefile/mage
go: finding github.com/magefile/mage v2.2.0+incompatible
go: finding github.com/magefile/mage/types latest
go build github.com/magefile/mage/types: no Go files in
```

**Comment by natefinch** [comment]
Modules are going to be the death of me, I swear :) 

I think Go was grumpy because there was no tagged version with a go.mod file.  Try it again, I just pushed up a 2.3.0 tag, which should hopefully fix the problems here.

**Comment by natefinch** [comment]
If you hit any problems with 2.3.0, please rerun with the -debug flag and post the results here.

**Comment by natefinch** [comment]
ok, so I did some horribleness and ripped out all usages of v2... mage will now stick to v1.x.  what was 2.3.0 is now 1.2.3, and 1.2.4 is current master.  I tried that and it seems to work with modules (I realized that if mage is v2, you have to change the module import path to have /v2 at the end... which I'm trying to avoid).

**Comment by natefinch** [comment]
Closing, since this seems fixed from my end.  Feel free to reopen if you hit any problems.

**Comment by nullstyle** [comment]
Thanks for the fix, I've updated to latest and my issue has been resolved!  I appreciate it :)
