### ISSUE TITLE
Provide binary for newer versions

### ISSUE THREAD

**Issue by Hanzei** [magefile/mage#149]
First of all thanks your very much for this project!

For v1.0.2 a release binary was provided. This made installations much easier. It would be great if binaries would also be available for newer releases like v1.2.4.

**Comment by natefinch** [comment]
Just did it.... was having some problems with goreleaser... it seems like it doesn't like it when there are lightweight tags in the repo.  Deleting those did the right thing (though the changelog for v1.2.4 includes a lot that was in earlier releases, but that's ok).
