### ISSUE TITLE
Mage fails on go tip (i.e. go1.12, master)

### ISSUE THREAD

**Issue by bep** [magefile/mage#150]
```bash
0.02s$ mage -v test
Error determining list of magefiles: failed to get version from go version output: go version devel +3e5b5d69dc Thu Sep 6 09:54:01 2018 +0000 linux/amd64
```

**Comment by natefinch** [comment]
Ahh crap. I'll have to fix that. I use go version to know whether to build
with modules or not.

I guess you're not running a released version of go?

**Comment by bep** [comment]
>I guess you're not running a released version of go?

I do. But this is on Travis: https://travis-ci.org/gohugoio/hugo

Those build failures do not "fail the build", but it is useful to get an early warning of any issues about the next Go version.

**Comment by natefinch** [comment]
I think this should be fixed in 1.3.0 btw... I'll check it in a bit.

**Comment by bep** [comment]
>I think this should be fixed in 1.3.0 btw... I'll check it in a bit.

Maybe if you could create the tag as "v1.3.0".

**Comment by natefinch** [comment]
Oh dammit. Stupid picky thing. I'll have to add a check to my magefile to ensure I don't screw this up.

**Comment by natefinch** [comment]
This is fixed. it's v1.3.0 (and there's a v1.4.0 with proper and tested go module support)
