### ISSUE TITLE
Namespaces and dependencies error: interface is nil, not error

### ISSUE THREAD

**Issue by jlucktay** [magefile/mage#165]
Following on from #154 I have a new error now.

I have run `go get -u github.com/magefile/mage` to get the new changes from #163, and my `mage` binary has been rebuilt very recently:
``` shell
$ ll $(type -p mage)
-rwxr-xr-x 1 jameslucktaylor staff 4.1M Sep 16 15:51 /Users/jameslucktaylor/go/bin/mage*
```

Some relevant code:
``` go
type (
	WebApp mg.Namespace
)

// Deploys and tests the web app.
func Def() {
	mg.Deps(WebApp.Deploy)
	mg.Deps(WebApp.Test, WebApp.Prune)
}
```
The first line which calls `WebApp.Deploy` which runs through OK, but the second line with `WebApp.Test` and `WebApp.Prune` gives back the following:
```
Error: interface conversion: interface is nil, not error
```
I can run `mage webapp:prune` and `mage webapp:test` individually from the command line without issue, so it looks like something inside `mg.Deps()` still doesn't like the namespaces.

**Comment by natefinch** [comment]
Yep, I see it.   Fix incoming.

**Comment by natefinch** [comment]
fixed with #166

**Comment by jlucktay** [comment]
Nice one, thank you!

**Comment by natefinch** [comment]
Awesome! :)
