### ISSUE TITLE
running mage with GOOS=foo influences the GOOS of the compiled magefile

### ISSUE THREAD

**Issue by natefinch** [magefile/mage#169]
iF you have a target that builds your code and you decide you want to run it with GOOS=windows ... Mage will try to compile the magefile with GOOS=windows, and if you're not on windows, it'll break.

i.e.

`GOOS=windows mage build`

will compile the magefile itself with GOOS=windows ... and then try to run it and fail if you're not on windows.

We need to isolate mage's own compilation from the standard environment variables, with the possibility of something like MAGEFILE_GOOS for when you want to produce a magefile binary of a specific os/arch.

**Comment by fbettag** [comment]
This is currently the only blocker for me to change most of my projects to magefile. Otherwise this is an absolutely awesome project! thanks!

**Comment by natefinch** [comment]
Ahh thanks for letting me know. I'll prioritize this, then.  Glad you like it! :)

**Comment by natefinch** [comment]
Oh, note that you can always specify the environment variable for commands that you run explicitly, so like 

```
sh.RunWith(map[string]string{"GOOS":"linux"}, "go", "build")
```

But it would be nice to isolate mage compilation itself.

**Comment by fbettag** [comment]
Yup i found that already :) but for our build system i need to pass GOOS/GOARCH for all the OSes/Arches we build for (which is almost all legit combos :P)

**Comment by natefinch** [comment]
So, I just had to do this for one of my own projects, and I just used a different name for the variables:
```
// Runs "go build" and generates the version info the binary.
// Use GOOSE to set GOOS and GOARCHE to set GOARCH on the output binary. 
func Build() error {
	env := map[string]string{
		"GOOS": os.Getenv("GOOSE"),
		"GOARCH": os.Getenv("GOARCHE"),
	}
	return sh.RunWith(env, "go", "build")
}
```

Not that I won't fix this, but this could be a fix in the meantime.
