### ISSUE TITLE
Any chance of a `mage' README badge?

### ISSUE THREAD

**Issue by naltun** [magefile/mage#178]
I'm working on a Go project and I am thinking of incorporating a Magefile. If so, I'd love to add a README badge if there's to be one. :)

**Comment by natefinch** [comment]
Amazing idea. There isn't one right now, but there could be!  What would you want it to display?  What would you want it to link to?

**Comment by naltun** [comment]
Hmmmmmmm

I think it should definitely link to either 1) the Magefile, or 2) [Magefile.org](https://magefile.org/), because, you know, the project rocks and I want people to know about it.

To display? Not sure actually. :) Also, it seems like the dominant color associated with Mage is purple, so maybe the badge color should be that.

**Comment by natefinch** [comment]
[![Build With Mage](https://img.shields.io/badge/built%20with-mage-gray.svg?longCache=true&style=popout-square&colorB=8451a1)](https://magefile.org) 

Something like that?

**Comment by naltun** [comment]
Love it. Wow, that purple is perfect.

Is it possible to add the wee gopher mage, too? Pizzazz, 'n' all.

**Comment by natefinch** [comment]
I was just writing that.... it doesn't work well on the purple background at that scale, but you could always put him after it:

[![Built With Mage](https://img.shields.io/badge/built%20with-mage-gray.svg?longCache=true&style=popout-square&colorB=8451a1)](https://magefile.org)<img src="https://npf.io/gary.svg" width=25px>

**Comment by naltun** [comment]
I'm okay with that. I wonder if there's a hack to get the wee guy in there nicely. But that's less important. I like the `built with: mage` badge. What do you think? Do you like it now that you're looking at it?

**Comment by natefinch** [comment]
I love the badge idea. I bet I can whip something up in Adobe illustrator that will work with the logo included.  using shields.io was the best I could do on short notice.

I could host it on magefile.org, then people could just put `<img src=magefile.org/badge.svg>` and link to whatever.

**Comment by naltun** [comment]
I love it, man.

**Comment by natefinch** [comment]
This is my favorite so far, but it looks best if it's big
<img src="https://magefile.org/badge-tall.svg" height=120px>
small is ok:
<img src="https://magefile.org/badge-tall.svg" height=40px>
I tried single line height, same as the regular badges, but I couldn't make it work with the mage image I have. Maybe I'll have to commission a special version that works at very small sizes.

**Comment by naltun** [comment]
_If_ it was possible to get the badge as a single-line height, then I think that would be perfect.

**Comment by natefinch** [comment]
I'll see if I can work something out. Maybe just the top half of the gopher
mage would work.

**Comment by natefinch** [comment]
Best I can do without commissioning new artwork (which could be a possibility:

<img src="https://npf.io/badge-01.svg">

**Comment by naltun** [comment]
IMHO I think you've got it with this one, man. :+1: I love it.

**Comment by natefinch** [comment]
https://magefile.org/badge.svg is now a thing :)
