### ISSUE TITLE
Windows: Mage stores cache files in current directory when run with elevated privileges

### ISSUE THREAD

**Issue by misha-tectonic** [magefile/mage#186]
If a shell is running with elevated privileges under Windows, `%HOMEDRIVE%` and `%HOMEPATH%` environment variables are empty, so cache files end up in "magefile\...".

`%USEPROFILE%` is still available!

**Comment by natefinch** [comment]
Oops, thanks for debugging this... I'll get a fix out. For now, you can set MAGEFILE_CACHE to ensure the binaries go somewhere unobtrusive.

**Comment by linkleonard** [comment]
Hi! I'd like to take a stab at this.

**Comment by natefinch** [comment]
Great, thank you!

**Comment by wojciech-tectonic** [comment]
Please examine the following screenshot:
![screen](https://user-images.githubusercontent.com/43376657/47003772-4c16d400-d130-11e8-9ee6-603a948b9a84.jpg)

On the left, powershell is run with elevated privileges (run as administrator option), on the right as regular user. As you can see environment variables are empty if powershell is started with admin rights. Screenshot was taken on Windows 10.

**Comment by danbrakeley** [comment]
Similar to @linkleonard , I do not see the problem either:
![image](https://user-images.githubusercontent.com/6772870/49390692-9f9cab80-f6f7-11e8-80ee-012f49c6efff.png)

@wojciech-tectonic A bit of googling shows this problem has crept up for a couple of other people as well: https://github.com/Microsoft/vscode/issues/21352

One user on [answers.microsoft.com](https://answers.microsoft.com/en-us/windows/forum/all/homepath-variable-has-disappeared/d1d12afd-4b06-4c6f-ba16-bd189fef198f) claims to have fixed it:

> That last reply I posted got me to thinking it might be a permissions problem, and it was.  The SYSTEM group somehow lost access rights to my home folder, and granting it permission solved the issue.

**Comment by misha-tectonic** [comment]
Seems to be a misconfiguration at @wojciech-tectonic's machine.
