### ISSUE TITLE
Improved dependency tracking?

### ISSUE THREAD

**Issue by sean-** [magefile/mage#191]
We use `mage` at `$WORK` and I've been looking around at other tools.  [`plz`](https://github.com/thought-machine/please) showed up and has pretty much rocked my world, but that isn't an outright replacement for what we're using `mage` for atm.  After a bit more digging, I ran into a library called [`build`](https://github.com/bldy/build) (or just https://bldy.build/build).  Has there been any thought to improving the dependencies in `mage` using a library such as `build`?

/me is still in shock that he'd never heard of https://please.build before recently and is still getting over this

**Comment by natefinch** [comment]
Can you describe what you'd like to see improved?  I'm not entirely sure how to use the ideas from build in mage.

**Comment by natefinch** [comment]
closed due to lack of response for two years :)
