### ISSUE TITLE
Aliases fail on imported namespaces

### ISSUE THREAD

**Issue by 200sc** [magefile/mage#192]
Given this Magefile at `site.go/project`:
```Go
// +build mage

package main

import (
	// mage:import
	"site.com/project/subfolder"
)

var Aliases = map[string]interface{}{
	"fizz": subfolder.Foo.Bar,
}
```

And this single go file being imported from `site.go/project/subfolder`:

```Go
// +build mage

package subfolder

import (
	"github.com/magefile/mage/mg"
)

type Foo mg.Namespace

func (Foo) Bar() error {
	return nil
}
```

The following warning is received on running `mage`: `warning: alias declaration (fizz) does not reference a mage target`

Following this, mage exits with status 1.

`mage -version` outputs:
```
Mage Build Tool v1.7.1
Build Date: 2018-10-31T09:48:07-05:00
Commit: 11d1591
built with: go1.11
```

This was built on `windows/amd64`

The behavior expected would be for `fizz` to be a valid alias to the target in the subfolder.

**Comment by natefinch** [comment]
So, when you import from another package, the code you import can't be marked with the `mage` build tag. However, even without the mage build tag, it still fails with that error.

I'll make a fix, it's probably something small and easy.
