### ISSUE TITLE
I added "//+build mage" on the first line in go file,but tip for me with  below info

### ISSUE THREAD

**Issue by yuyongbo** [magefile/mage#196]
No .go files marked with the mage build tag in this directory.

**Comment by yuyongbo** [comment]
![image](https://user-images.githubusercontent.com/17313948/48262654-4fb32780-e45e-11e8-98ff-1b7498d1a543.png)

**Comment by natefinch** [comment]
You need a blank line before the package declaration.  Note that there's a squiggly line under that comment, I bet if you hover the mouse over it, it'll tell you that, too.  If there's no blank line then the go tool treats it as documentation about the package, instead of a build tag.

**Comment by yuyongbo** [comment]
yeah, that work on, I hadn`t noticed before ,thanks,I was too careless!
