### ISSUE TITLE
Feature request: Simplest, and second simplest, examples plz :)

### ISSUE THREAD

**Issue by aprice2704** [magefile/mage#198]
Heya Nate and crew,

I think Mage looks nifty, but it would really help lazy and/or stupid people, like me, if you could include a couple of *simple* worked examples prominently on the main help pages. I'm sure the video is good (I am about to watch it), but still, the text version would be nice just to get people over the initial learning hump and get to "yes, this will be useful for me" quickly. :)

Thanks
Andy

**Comment by natefinch** [comment]
Cool, yeah, I can put up a few simple examples.  

Something like this?

```go
//+build mage

package main

// Runs dep ensure and then installs
func Build() error {
    if err := sh.Run("dep", "ensure"); err != nil {
        return err
    }
    return sh.Run("go", "install", "./...")
}
```

**Comment by aprice2704** [comment]
Yes exactly! :)

**Comment by natefinch** [comment]
Done!
