### ISSUE TITLE
The description is misleading.

### ISSUE THREAD

**Issue by gordonklaus** [magefile/mage#2]
"a Makefile replacement for go" gives the impression that this is a tool for building Go code.   "A tool for writing Makefiles using Go" might be better.

**Comment by natefinch** [comment]
Good point, I'll clarify :)

**Comment by natefinch** [comment]
Fixed, I hope!   `a Make/rake-like build tool using Go`

**Comment by gordonklaus** [comment]
Much better 😄 

The leading line of the README should be tweaked, too.

**Comment by natefinch** [comment]
Ahh yeah, thanks. Done! :)
