### ISSUE TITLE
build mage with mage

### ISSUE THREAD

**Issue by natefinch** [magefile/mage#20]
we should have a magefile to build all release targets

For now, we don't need a general build target, but it might be worth making one just so people can see how it works.

**Comment by natefinch** [comment]
Here's an example that builds everything for gnorm:
https://github.com/gnormal/gnorm/blob/master/mage.go

**Comment by klud1** [comment]
Maybe it would also be possible to create Mage tasks? (As in Rake tasks)

**Comment by natefinch** [comment]
can you talk about how that differs from a make target?  I can Google, but sometimes a human description helps.
