### ISSUE TITLE
sh.Copy does not close destination file descriptor

### ISSUE THREAD

**Issue by jonasrmichel** [magefile/mage#222]
The `sh.Copy` function successfully closes the `source` file descriptor, but leaves the `destination` file descriptor open when the function returns. 

On Windows, this causes an error if the `destination` file is later deleted. The following error is produced.
```
The process cannot access the file because it is being used by another process.
```

**Comment by natefinch** [comment]
Yikes! Yep, I can see I forgot the defer there.  Thanks for bringing this up!
