### ISSUE TITLE
Mage installation seems to ignore GOBIN

### ISSUE THREAD

**Issue by justinclift** [magefile/mage#231]
Trying out Mage atm (mostly to investigate Hugo's test setup).  When following the install instructions (using `GOPATH`), the resulting binary is placed in `bin/` under one of the paths in GOPATH.

Which seems weird, as my environment has `GOBIN` set to the correct location (not where it ended up).

Kind of wondering if ignoring `GOBIN` is on purpose for some reason, or if it's just a case of needing a PR to get it fixed? :smile:

**Comment by natefinch** [comment]
yup, needs a PR.  Honestly, maybe we should just use go build and not try to be smart about where we put the mage binary.   but either way it needs a PR.  Offending code is in the install target here: https://github.com/magefile/mage/blob/master/magefile.go#L30

**Comment by justinclift** [comment]
Thanks @natefinch, I'll probably get to it sometime in the next few days. :smile:

**Comment by justinclift** [comment]
Got to it sooner than expected.  Seemed pretty simple to fix, and work with/without GOBIN being in the environment.  Shouldn't have a negative impact. :smile:
