### ISSUE TITLE
Cannot Pass Go Build Flags to Mage

### ISSUE THREAD

**Issue by WarLlama** [magefile/mage#233]
Mage executes the `gocmd` without allowing you to pass any build flags to it. This breaks the ability to use mage with modules that use vendored dependencies. 

I am using mage to build a go project that uses go modules and a vendor folder. However, mage calls the go executable without any flags, so it tries to pull down the module dependencies anyway.

Example line: https://github.com/magefile/mage/blob/master/mage/main.go#L428

```
# ./build/go/bin/go run -mod vendor mage.go -debug build
DEBUG: 19:11:51.177604 getting all non-mage files in .
go: finding github.com/smartystreets/assertions v0.0.0-20190215210624-980c5ac6f3ac
...
...
...
go: error loading module requirements
DEBUG: 19:11:52.401965 time to scan for Magefiles: 1.224378059s
Error determining list of magefiles: failed to list non-mage gofiles: exit status 1
exit status 1
```

Using the `-compile` flag isn't an option either, since mage is calling `gocmd` via `os/exec`

**Comment by natefinch** [comment]
can you try running with `GOFLAGS=-mod=vendor` ?  I think that might work

**Comment by WarLlama** [comment]
That looks like it works. Thanks
