### ISSUE TITLE
Magefile with local server causes endless Windows Firewall nagging

### ISSUE THREAD

**Issue by mitranim** [magefile/mage#237]
My magefile starts a local server. Just like with any other program that runs a server, Windows Firewall gives me a one-time security notification about it. This "one-time" behavior is tied to the executable path, and under Mage, the executable name changes on every rebuild (I assume it's the source hash for reuse). I briefly checked the firewall settings, but haven't found a way to exclude a directory or use a wildcard. I'll keep looking for a solution; would be nice to hear suggestions. If we find one, it should probably be included into the docs.

**Comment by mitranim** [comment]
One simple solution is to partially disable those notifications:

![image](https://user-images.githubusercontent.com/4263831/55898468-54c20180-5bcb-11e9-8c5c-1a6f2367ce3e.png)

This basically says "yeah use the default blocking behavior", which tends to be just fine.

**Comment by natefinch** [comment]
hmm... interesting.. yeah, the fact that it's a randomly named executable starting up a server, not surprised the firewall is complaining.  The name is the hash of the magefiles, exactly for reuse. 

One solution could be to let you configure the output binary's name, specifically for this purpose. You'd have a possibility of stomping over an existing binary with the same name in your mage cache, but that's not terribly likely, nor a huge problem (just means you'd have a longer build time if you ran the "other" magefile that used the same output name).

Another possibility which may or may not fit your use case is to use the `-compile` flag to produce a binary with a name you give it (i.e. you can do `mage -compile ./foo.exe` and then configure the firewall to ignore foo.exe).

**Comment by mitranim** [comment]
A consistent executable name seems generally nice. It would play well with firewalls, be easy to find in your process list when it inevitably runs an infinite loop, and be more like all other programs, which all have static names. On the other hand, I like the simplicity of hashes, which makes them easy to find without any additional book-keeping. We could generate a static but unique name from, say, the magefile directory path, but invalidating an executable might require an additional file that associates it with the hash. You probably have better ideas.

Precompilation seems rather inconvenient in a task runner, especially if the magefile changes often, as I'm sure you understand.

For now I'm satisfied with the solution above, the firewall defaults seem acceptable anyway. We could kick around some ideas; feel free to close the issue.

**Comment by natefinch** [comment]
Closing this for now.  I don't think many people run servers from a magefile, and the -compile thing seems an ok solution currently.
