### ISSUE TITLE
Error: error compiling magefiles

### ISSUE THREAD

**Issue by milesje** [magefile/mage#239]
I'm getting a strange error that I don't know how to fix or how to figure out why.
System:
OS: Windows 10 x64
CPU: Intel Core i7-7500U
Go Version: 1.12

```
go get -u -d github.com/magefile/mage
cd $GOPATH/src/github.com/magefile/mage
go run bootstrap.go   <-- errors out here
```

```
go run bootstrap.go
go build command-line-arguments: mkdir H:: The system cannot find the path specified.
Error: error compiling magefiles
exit status 1
```

**Comment by milesje** [comment]
mage -debug -l
DEBUG: 10:21:06.867691 getting all non-mage files in .
DEBUG: 10:21:07.338191 found non-mage files main.go
DEBUG: 10:21:07.338191 marked file as non-mage: "main.go"
DEBUG: 10:21:07.338694 getting all files plus mage files
DEBUG: 10:21:07.713697 time to scan for Magefiles: 846.0014ms
DEBUG: 10:21:07.713697 found magefiles: magefile.go
DEBUG: 10:21:07.813065 output exe is  H:\magefile\bba96db316c5629968e2dc1b8d1d22b5800f4815.exe
DEBUG: 10:21:07.913048 build cache exists, will ignore any compiled binary
DEBUG: 10:21:07.913195 parsing files
DEBUG: 10:21:07.913701 found target Build
DEBUG: 10:21:07.914197 found target Clean
DEBUG: 10:21:07.914197 found target Install
DEBUG: 10:21:07.914197 found target InstallDeps
DEBUG: 10:21:07.914697 time parse Magefiles: 1.5021ms
DEBUG: 10:21:07.915197 Creating mainfile at mage_output_file.go
DEBUG: 10:21:07.915701 writing new file at mage_output_file.go
DEBUG: 10:21:07.923701 compiling to H:\magefile\bba96db316c5629968e2dc1b8d1d22b5800f4815.exe
DEBUG: 10:21:07.923701 compiling using gocmd: go
DEBUG: 10:21:08.274197 running go build -o H:\magefile\bba96db316c5629968e2dc1b8d1d22b5800f4815.exe magefile.go mage_output_file.go
go build command-line-arguments: mkdir H:: The system cannot find the path specified.
DEBUG: 10:21:08.986109 time to compile Magefile: 688.4059ms
Error: error compiling magefiles

**Comment by milesje** [comment]
Why is the output exe H:\magefile\bba96db316c5629968e2dc1b8d1d22b5800f4815.exe?
I don't have an H drive on my system.

**Comment by milesje** [comment]
It seems to work fine on my Linux PC, but not on my Windows 10 Laptop.

**Comment by natefinch** [comment]
It uses `%HOMEDRIVE%\%HOMEPATH%\magefile` on windows .   maybe HOMEDRIVE is set to H?

**Comment by milesje** [comment]
OK, the laptop is a company machine and I don't have the permissions needed to change what the %HOMEDRIVE% and %HOMEPATH% environment variables are set to. I have a request sent into my company IT, but I doubt they are willing to change it.

**Comment by natefinch** [comment]
you can set MAGEFILE_CACHE to wherever you want mage to store the generated binaries

**Comment by milesje** [comment]
Thanks, setting the MAGEFILE_CACHE fixes my issue.

**Comment by FreerideTheWorld** [comment]
Where is the MAGEFILE_CACHE setting that I need to change to fix this error?

**Comment by natefinch** [comment]
What error are you seeing, @FreerideTheWorld ?  if it seems the same, then this is just an environment variable that you can set to tell mage where to create its compiled binaries (it compiles the magefile.go into a temporary binary that then gets run).  You can set it to whatever you like, just someplace that won't get cleaned out by accident.

**Comment by FreerideTheWorld** [comment]
C:\Users\RDowney\go\src\github.com\magefile\mage>go run bootstrap.go
go build command-line-arguments: mkdir O:: The system cannot find the path specified.
Error: error compiling magefiles
exit status 1

Thats the error I'm just lost as to where to actually change the environment variable.  I'm assuming that its just a quick change to a file but we all know where assumptions can get you.

**Comment by natefinch** [comment]
Yeah, normal old windows environment variables. You can set it for your user to `C:\Users\RDowney\.mage` or something.

**Comment by FreerideTheWorld** [comment]
@natefinch, I was able to get this running by setting the variable name to MAGEFILE_CACHE and variable value to C:\Users\RDowney\.mage in the Environment -> System Variables.  Thank you for the help and the quick response.  Now I have to troubleshoot the other path errors that I'm getting, lol, its a never-ending process when this is all new to you.  Those arent mage issues so I'll be spending some time watching GitHub tutorial :). Again, thanks for the assistance!
