### ISSUE TITLE
Magefiles dependencies in go.mod

### ISSUE THREAD

**Issue by ntrrg** [magefile/mage#243]
Hi, if you try to import any library using Mage, you will download Mage as a dependency. You can try that with Hugo:

`main.go`

```go
package main

import (
	"fmt"

	"github.com/gohugoio/hugo/livereload"
)

func main() {
	fmt.Printf("%s\n", livereload.Handler)
}
```

```shell-session
$ go mod init go-test
$ go run main.go
```

The reason is because the `go.mod` file from Hugo includes Mage and any other magefile dependency in it

**Comment by natefinch** [comment]
Yes. That's how dependencies work. Mage is a dependency of hugo's code. If you run `go mod tidy` it might clean up the dependencies you don't actually need from hugo's transitive dependencies, but I'm not 100% sure on that. 

This is similar to when you import a library that uses 3rd party test libraries... those get put into your dependencies as well. This is basically unavoidable.

**Comment by ntrrg** [comment]
Yes, I know that this is not actually a Mage issue, but we could avoid it providing something like a `-D` flag for setting the working directory of the compiled magefiles, so you could put all your magefiles in other directory (`.mage` for example) and run mage as `mage -d .mage -D .`, that way the `go.mod` file doesn't get populated with magefiles dependencies

**Comment by natefinch** [comment]
So, I think this is partly a bug of -d that it sets the working directory to the -d directory. I had intended it to take the directory you're in as the working directory.  I wonder if it's too late to make -d work that way...   but separating that out might be better.

**Comment by ntrrg** [comment]
I was thinking the same, but there could be someone relying on that behavior, so I wasn't sure how important is keeping it in that way. I did tried getting this working and just some lines were needed
