### ISSUE TITLE
mage doesn't look in vendor

### ISSUE THREAD

**Issue by edgarm1964** [magefile/mage#244]
Hi,

  I'm forced to use mage (I'm building an elastic search beat and I'm running "make ci") and mage doesn't look in the **vendor** directory (only in **src**):

```
execbeat$ GOPATH=${PWD} mage
magefile.go:10:2: cannot find package "github.com/magefile/mage/mg" in any of:
        /Users/edgarm/tools/go/src/github.com/magefile/mage/mg (from $GOROOT)
        /Users/edgarm/Projects/github.com/edgarm1964/execbeat/src/github.com/magefile/mage/mg (from $GOPATH)
Error: error compiling magefiles
```

The question is why?

General complaint: Why is golang enforcing a build/src structure? ${GOPATH}/src? Golang is a toy.

**Comment by natefinch** [comment]
You shouldn't be setting GOPATH to your current working directory.  If you're using GOPATH, you need your code to live at $GOPATH/src/github.com/edgarm1964/execbeat . 
If you haven't explicitly set GOPATH, it will be interpreted as /Users/edgarm/go 

It looks like beats uses glide for vendoring, which means your code still needs to live in GOPATH.  (this will be fixed when/if beats moves to using go modules, which can live anywhere you want, like your Projects directory).

**Comment by edgarm1964** [comment]
OK, good to know. Thanks.
