### ISSUE TITLE
when using a compiled mage binary, the verbose flag isn't propagated

### ISSUE THREAD

**Issue by Oneymus** [magefile/mage#248]
When using a pre-compiled static `mage` binary, the `-v` flag does not produce the proper output.

Using this simple example:
```go
func ShowVerboseDep() error {
	sh.Run("echo", "hello, mage!")
	return nil
}

func ShowVerbose() error {
	mg.Deps(ShowVerboseDep)
	sh.Run("echo", "goodbye, mage!")
	return nil
}
```

Output:
```bash
$ mage -v showverbose
Running target: ShowVerbose
Running dependency: ShowVerboseDep
exec: echo hello, mage!
hello, mage!
exec: echo goodbye, mage!
goodbye, mage!
```

```bash
$ ./mage -v showverbose
Running target: ShowVerbose
exec: echo hello, mage!
exec: echo goodbye, mage!
```

We're missing both the shell output and the dependency log lines.

When using the `mage` command directly, `mage` sets the `MAGEFILE_VERBOSE` environment variable based on the `-v` flag (see [here](https://github.com/magefile/mage/blob/master/mage/main.go#L611)).

However, the generated `mage_output_file.go` from which the compiled binary is built does no such thing.

This is relevant because both `sh` and `mg` inspect the `MAGEFILE_VERBOSE` environment variable (see [here](https://github.com/magefile/mage/blob/master/mg/runtime.go#L30-L34)); there doesn't appear to be any other way to signal to these libraries that we want verbose output.

I propose we update the generated `mage_output_file.go` to set the `MAGEFILE_VERBOSE` environment variable just like we do for the `mage` command.

**Comment by philipsahli** [comment]
I observed the same issue some days ago. My workaround is to add the variable in an init function, because at the moment I feel that in any case the output of the commands are interesting: 

    // When using a static binary (by doing `mage -o gob`, the arg `-v` seems to be ignored.
    os.Setenv("MAGEFILE_VERBOSE", "1")
