### ISSUE TITLE
Add a way to pipe stdout from one command to stdin of another

### ISSUE THREAD

**Issue by wfscheper** [magefile/mage#254]
Some tools work exclusively by receiving data on stdin (the gocov family of tools is my particular use case) and currently can't easily be used within a magefile. I'm proposing to add three new functions to mage/sh: Pipe, PipeCmd, and PipeWith. These would be similar to the equivalent Out* commands, except they would take an extra argument that is an io.Reader that will be attached to the Commands Stdin.

I already have a branch with a first pass at implementing these functions as a starting place for discussion: [wfscheper/mage](https://github.com/wfscheper/mage/tree/pipe-commmands).

A contrived example of using Pipe to do the equivalent of `cat /some/file | sort` would look like:
```
cat, _ := sh.Output("cat", "/some/file")
out, _ = sh.Pipe(strings.NewReader(cat), "sort")
```

**Comment by natefinch** [comment]
I feel like, at some point, people just need to use os.Exec. There are also other libraries out there, including https://godoc.org/gopkg.in/pipe.v2  which does pipe-like things, or https://github.com/bitfield/script that does everything without shelling out (which is honestly your best bet, to keep your magefiles platform agnostic).

**Comment by wfscheper** [comment]
Sure, mage as a project needs to draw a line around what level of complexity it supports out of the box.

Would it make sense to add a magefile/contrib project where people can submit extensions to mage that go beyond what the core project is willing to support? I know of several OSS projects that use a similar model and even use the contrib project as an incubator for eventual inclusion into the main library.

**Comment by natefinch** [comment]
I like that a lot, actually.  a contributor / incubator project sounds awesome

**Comment by wfscheper** [comment]
I'm going to close this ticket. Should I open a new ticket for discussion around a contrib project? Either way, I'm willing to help with maintaining a contrib project.

**Comment by natefinch** [comment]
Yes, let's talk about the contrib project in a new issue, thanks!
