### ISSUE TITLE
Custom dependency types

### ISSUE THREAD

**Issue by misha-ridge** [magefile/mage#255]
`mg.[Serial][Ctx]Deps` hardcode allowed dependencies to be 8 kinds of functions, and don't allow extending them.

I have a PR that makes those functions accept any object that can identify itself for uniqueness purposes, and can be run with a context. This PR adds an example of using this interface to safely implement parameterized dependencies.

**Comment by misha-tectonic** [comment]
See #256

**Comment by natefinch** [comment]
This is cool, but I wonder if it's too fiddly for people. One of the things I like about mage is how intuitive it is (or at least, it's intuitive for me).  This feels like adding methods to implement sort.Interface - functional, but not intuitive.

What use case does this solve?

**Comment by misha-tectonic** [comment]
Parameterized targets mostly.

It's quite tedious to write a lot of wrappers similar to
```
// BuildBlahNative builds blah for native platform
func BuildBlahNative() {
  buildBlah(platform.Native)
}
// BuildBlahDocker builds blah for Docker
func BuildBlahDocker() {
  buildBlah(platform.Docker)
}
```
to let `mg.Deps` distinguish the invocations, and it is impossible if the set of values for arguments is not known beforehand.

In addition, some of our targets have arguments that are not basic types (e.g. dates), so there should be an additional step of converting those arguments to something that can be used as a key for dependency management.

**Comment by natefinch** [comment]
ooh, yeah, ok I get it.  

I feel like there has to be a better way to do this, but maybe not.  Definitely problem, especially if we add support for parameterized targets from the CLI.

**Comment by natefinch** [comment]
Dang,  I swear I responded to this when I put the label on it.  

This seems to mostly be for the purposes of making something like

`mg.Deps(Foo("bar"))`

work the way you'd hope it to work.  While I agree that it would be great to make that work, I'm not sure this is the best way to go about it.  I feel like there must be a better way to do this, if I knew go internals and reflection and such better.  Like, I want it to Just Work, not require someone to fill out an annoying interface that they could potentially screw up if they're not careful.

**Comment by misha-tectonic** [comment]
I'd be satisfied with `mg.Deps(Foo{"bar"})`, if that works.

The problem with interface is `Identify()`, right?

In simple cases (members of primitive types and of types that implement `Stringer`) it can be generated automatically. Or maybe even better: a JSON serialization can be used as a key, so that `json:...` metadata can be used for customization. WDYT?

P.S: Note that first commit "Turn 8 mg.Deps() dependency types into an interface" does not change any external interfaces, it only tidies up internals a bit, so that the change like proposed in this comment can be done easier.

**Comment by natefinch** [comment]
This now works.  There's an mg.Fn interface that you can fulfill, but probably most people will just want to use mg.F to generate a dependency from a function and its arguments.
