### ISSUE TITLE
Add RunVWith

### ISSUE THREAD

**Issue by eberkund** [magefile/mage#260]
We have `mg.RunV`, it would be nice to also have `mg.RunVWith`. I've tried setting `MAGE_VERBOSE` in the map I pass into `mg.RunWith` but it doesn't seem to work.

**Comment by natefinch** [comment]
Yeah, that's a missing method, for sure.

**Comment by eberkund** [comment]
I'll submit a PR

**Comment by gbrlsnchs** [comment]
> I've tried setting MAGE_VERBOSE

The correct flag is `MAGEFILE_VERBOSE` and it is working for me. However, I do agree having `RunVWith` would be good.
