### ISSUE TITLE
Allow per-directory (local) config with .magefile

### ISSUE THREAD

**Issue by Bradbev** [magefile/mage#264]
The slack channel doesn't appear to be open access, so hopefully it's ok to discuss here.

I would like to build my directory structure such that from the root level I can run mage commands, but I don't want to have my .go files in that root.  Ie, essentially I need to run "mage -d ./build", but don't really like the extra "-d ./build" tokens.
I was considering adding a .magefile to the root directory that mage would load and would allow various configs to be specified.  
Does something like this already exist?  Is this a useful suggestion?

Thanks!
Brad

**Comment by natefinch** [comment]
First off, this is perfectly fine to bring up here.  It's basically a proposal, so no worries.

Slack doesn't really *do* "open" servers, so you have to do some rigamarole to get invited.  If you'd like to join the gopher slack (and I suggest you do, it's a great resource), you can get yourself an invite here: https://invite.slack.golangbridge.org/

Alternatively, there's a mage-specific discussion group here: https://groups.google.com/forum/#!forum/magefile
(though no one has actually used it yet).

But like I said, this is fine to post here.

I guess I don't understand why a .magefile in the current directory is ok, but a magefile.go is not ok. I guess maybe if you have a whole bunch of magefiles, that could get cluttery....

This would add yet another way to control mage's configuration, beyond environment variables and the command line.  Maybe a better solution would be to add an environment variable that does what -d does, and then you could use [direnv](https://direnv.net/) to set that in the local directory. 🤔  I'm not sure.  What do you think?

**Comment by Bradbev** [comment]
Thanks for the invite link - signed up.  Also, thanks for lumberjack - a package I've used for a year now & it's awesome.
A single magefile.go in the root directory would be fine, and if that file during compile could direct mage to look at another directory, that would also be fine.  Now that I say that I seem to recall something with imports that might let me do this.
My usage scenario is a large multiplatform, monorepo system.  We build on windows and linux, and target Win32, LinuxARM/x86 with various techstacks (C++, Go, Angular, Android).  Keeping as platform agnostic as possible is a goal.  Our current python based build system is thousands of lines & quite the mess.  So while I don't currently have tens of magefiles, I think it's reasonable to assume I will eventually.  At which point it would get a bit cluttery in the various root directories.
An environment var to trigger -d would solve the issue I think.

What's your preference?  Would you accept a PR that implements the environment var method?

**Comment by natefinch** [comment]
So I think mage imports will do what you want (maybe).

You can have a single magefile.go in the root that just has this: 

```go
//+build mage

package main

// mage:import
import _ "github.com/myco/myrepo/build"
```

Then that will duplicate all the targets from the subdirectory "build" as if they were defined in this magefile.

The two things it doesn't duplicate is aliases and a default target.  If you use those a lot, what might be a good PR is an addition allowing those to get set to values in other packages, like this:

```go
var Default = build.Default
var Aliases = build.Aliases
```
(currently, I am pretty sure that doesn't work)

**Comment by Bradbev** [comment]
That gets me close to what I want - I think.  I'll need to actually do some implementation to see exactly where the issues are I think.
I'm going to close this issue now.  I need more real usage experience before deciding on the best solution for me, and you've given me a couple of options to explore further.
Thanks very much!
Brad
