### ISSUE TITLE
mage_output_file.go generated with missing targets

### ISSUE THREAD

**Issue by wfscheper** [magefile/mage#276]
I have a project that is basically a library of mage targets. There are targets defined in several sub-packages and two in the root package. I recently added a magefile so that I could use some of the targets in the library on the library itself, however I occasionally encounter this error when using the magefile:
```
$ go run mage/mage.go -l -debug
DEBUG: 23:39:27.668073 getting all non-mage files in .
DEBUG: 23:39:27.757209 found non-mage files magetest.go
DEBUG: 23:39:27.757232 marked file as non-mage: "magetest.go"
DEBUG: 23:39:27.757235 getting all files plus mage files
DEBUG: 23:39:27.795015 time to scan for Magefiles: 126.974683ms
DEBUG: 23:39:27.795036 found magefiles: magefile.go
DEBUG: 23:39:27.805403 output exe is  /Users/wasche/.magefile/8770b1cb20f3d900f5bebc4498ad7ffa9ba7a519
DEBUG: 23:39:27.816255 go build cache exists, will ignore any compiled binary
DEBUG: 23:39:27.816271 parsing files
DEBUG: 23:39:27.816620 time parse Magefiles: 342.668µs
DEBUG: 23:39:27.816631 found mage:import: github.com/wfscheper/magetest
DEBUG: 23:39:27.816634 found mage:import: github.com/wfscheper/magetest/foo (foo)
DEBUG: 23:39:27.816641 getting import package "github.com/wfscheper/magetest/foo", alias "foo"
DEBUG: 23:39:27.909592 parsing imported package "github.com/wfscheper/magetest/foo" from dir "/Users/wasche/git/magetest/foo"
DEBUG: 23:39:27.909984 found target Foo
DEBUG: 23:39:27.910016 time parse Magefiles: 397.002µs
DEBUG: 23:39:27.910020 setting alias "foo" and package "foo" on func Foo
DEBUG: 23:39:27.997637 parsing imported package "github.com/wfscheper/magetest" from dir "/Users/wasche/git/magetest"
DEBUG: 23:39:27.998022 time parse Magefiles: 356.197µs
DEBUG: 23:39:27.998042 Creating mainfile at mage_output_file.go
DEBUG: 23:39:27.998165 writing new file at mage_output_file.go
DEBUG: 23:39:27.998814 compiling to /Users/wasche/.magefile/8770b1cb20f3d900f5bebc4498ad7ffa9ba7a519
DEBUG: 23:39:27.998820 compiling using gocmd: go
DEBUG: 23:39:28.135084 running go build -o /Users/wasche/.magefile/8770b1cb20f3d900f5bebc4498ad7ffa9ba7a519 magefile.go mage_output_file.go
# command-line-arguments
./mage_output_file.go:19:2: imported and not used: "github.com/wfscheper/magetest" as magetest_mageimport
DEBUG: 23:39:28.304639 time to compile Magefile: 169.424177ms
Error: error compiling magefiles
exit status 1
```

Running with `-keep` reveals that mage detected the `magetest` top-level import, but somehow failed to parse any targets, thus the unused import that causes the compile failure.

I have made a simple git repo that reproduces the issue at https://github.com/wfscheper/magetest. There are two other branches in that repo: working and dot-import. The [working](https://github.com/wfscheper/magetest/tree/working) branch shows the only way I've found to get this to work. The [dot-import](https://github.com/wfscheper/magetest/tree/dot-import) branch is an example of an attempted work-around that still exhibits the same problem.

**Comment by mirogta** [comment]
I'm experiencing the same issue, but it is very intermittent.

I keep running `mage -f` and tried also `mage -f -keep` and can also see that the `mage_output_file.go` does not have generated targets from my package, which is in the same repository.

Unfortunately, it's very random. I've ran it about 20 times and kept getting this error
```
./mage_output_file.go:19:2: imported and not used: "github.com/<user>/<repo> as protobuf_mageimport
Error: error compiling magefiles
```
... but without changing any source code, on 21st attempt it has worked and shown me all the expected targets in the output. Then again about 20 runs were with the above failures and then again one occurrence of a working code.

@natefinch what could possibly cause this non-deterministic compilation?

**Comment by natefinch** [comment]
Thanks for pinging me on this, let me investigate, sorry I missed this earlier.

**Comment by mirogta** [comment]
> Thanks for pinging me on this, let me investigate, sorry I missed this earlier.

no problem :)

**Comment by natefinch** [comment]
I found it - the parsing code is returning the name of a package, but since there's two packages in the directory (main and magetest), and the returned value is a map, it's getting a randomized package... when it returns magetest, it works, when it returns main, there's no targets, so it fails.
https://github.com/magefile/mage/blob/master/parse/parse.go#L675

Trying to figure out the right way to fix it.  What I want is to only consider files that don't have build tags in them, but the parsing code is evidently returning all packages in the file, even those with build tags that should be excluded.

**Comment by natefinch** [comment]
tada!

**Comment by mirogta** [comment]
Awesome, thank you! looking forward to a new release
