### ISSUE TITLE
Homepage for magefile.org is broken

### ISSUE THREAD

**Issue by robinkb** [magefile/mage#282]
Hello!

I just noticed that the Magefile homepage at [magefile.org](https://magefile.org/) is broken. It now has a message that literally says that the site is not working, and lists the needed steps to take to fix the problem.

(And while I'm here, thank you for the wonderful tool!)

**Comment by natefinch** [comment]
Thank you.  It's fixed now.  There's some weird bug with netlify or maybe Hugo that causes this error when the website updates but then I re-trigger the auto build and it works the second time, even with no changes to the repo.  Super annoying.
