### ISSUE TITLE
Explicitly mention availability of brew installation in docs

### ISSUE THREAD

**Issue by neilotoole** [magefile/mage#288]
There's a `brew` formula available for `mage`: it should be explicitly mentioned in the repo `README.md` and on [magefile.org](https://magefile.org).

It really makes life easier to sell the usage of `mage` to skeptics if you can say to do this:

```
$ cd my/repo
$ brew install mage
$ mage install
```

Previously I'd been go-getting `mage` and using `bootstrap.go` etc... that was more effort than required (it's so simple with `brew`) and I saw pushback against the use of `mage` for that reason. I didn't know there was a `brew` formula. It's not in the docs, or at least, not obvious.

The website docs and `README.md` should be updated to reflect how easy it is to install `mage` via `brew`.

P.S. `mage` is wonderful. I was a minor skeptic initially, but I'm sold. Well done.

Related: #234

**Comment by natefinch** [comment]
Ahh, cool, I honestly didn't know there was a brew formula for it :)  I should add that to how we release, and yeah, definitely add it to the docs.
