### ISSUE TITLE
Added to Wikipedia

### ISSUE THREAD

**Issue by ghostsquad** [magefile/mage#296]
I added a link to Mage in Wikipedia here:
https://en.wikipedia.org/wiki/List_of_build_automation_software#Make-incompatible

Thought you would want to know, maybe link back to Wikipedia in the readme to show users of alternatives (help them decide what is the right tool for the job)

**Comment by natefinch** [comment]
Neat, thank you!

**Comment by paulburlumi** [comment]
It looks like this got [reverted](https://en.wikipedia.org/w/index.php?title=List_of_build_automation_software&type=revision&diff=965188840&oldid=965061243) on Jun 29, 2020.
The following comment was added:
```Xml
<!--
  Only add links to Wikipedia articles! Red links, bare URL links or unlinked entries are not acceptable.
  When in doubt, discuss the software on the talk page before adding here.
//-->
```
Shame 🙁

**Comment by mirogta** [comment]
Does it mean there just needs to be a top level Mage (software) page and then the link could be put back?

**Comment by paulburlumi** [comment]
That's my reading of it. Probably best to confirm this on the talk page first.
