### ISSUE TITLE
Can't use mg.Deps with dynamically generated functions

### ISSUE THREAD

**Issue by natefinch** [magefile/mage#309]
A lot of people want to be able to use mg.Deps to control dependencies that are generated on the fly. Unfortunately, the way mg.Deps does run-exactly-once builds is to use a map of functions by their name in the code. This works fine for functions and methods defined in code, but doesn't work for functions values returned by code.

e.g.

```go
func Build() {
	mg.Dep(buildDir("dir1"), buildDir("dir2"), buildDir("dir3"))
}
func buildDir(path string) func() {
	return func() {
		changed, err := target.Dir(path, ".")
		if changed {
			// do something with directory...
		}
	}
}
```

The current code uses runtime.FuncForPC().Name, to get the full name of the function, here: 

https://github.com/magefile/mage/blob/310e198ebd9303cd2c876d96e79de954915f60a7/mg/deps.go#L187

It seems like there has to be a way to do this, so that if you pass a value that is a hard coded function, you use the name of the function, but if you pass something that isn't a hard coded function, you just maybe use the pointer value or something.  

here's some code showing the problem of duplicate names for generated functions:

https://play.golang.org/p/3RrKWAzQpzE

**Comment by 5nord** [comment]
I'd argue `mg.Deps` is correct: It executes every function (-literal) just once. In Go there is no notion of pure functions, hence we cannot know if calling `buildDir("dir1")` twice yields the same closure.

**Comment by natefinch** [comment]
Actually, I think I have an idea. We could provide a wrapper that has a unique id that mg.Deps understand.

something like

```go
f := mg.F(buildDir("dir1"))
mg.Deps(f)
```
Under the hood, mg.F would wrap the function value in a type that provides a `func MageDepID() string` method which returns a unique id, and then mg.Deps could use that as the id for the function.

Someone else suggested something like this a while ago, but I never connected that it could so easily fix this problem.

**Comment by 5nord** [comment]
I like the idea with the wrapper function. However I think the mechanics when this function should be used, are not very clear to the average user.
I'd suggest to provide wrapper function `mg.Always` which marks the function to be executed always, similar to a `.PHONY`-target in Make:

```
mg.Deps(mg.Always(buildDir("dir1")), mg.Always(Build))
```


**Implementation**

`mg.Deps` should accept an interface `Target`:
```
type Target interface {
        Run(ctx context.Context) error
        NeedsUpdate(ctx context.Context) bool
}
```

Package mg would provide two concrete Implementations:
```
type struct onceFun { ... }
...

type struct alwaysFun { ... }
func (*alwaysFun) NeedsUpdate(context.Context) { return true }

func Always(fn interface{}) *alwaysFun { return &alwaysFun{fn:fn} }
```

**Comment by natefinch** [comment]
The thing about Deps is that the whole point is to avoid rerunning the same code. If you want to always run the function, just call the function.  

It sounds like what you're looking for is an easy way to run functions in parallel.  That would probably be different than mg.Deps, though probably would have some similar code.

**Comment by natefinch** [comment]
Ok, so I figured out some problems with my mg.F function that need to be tweaked... I was thinking it could generate the ID itself, but then it can't tell if it's called with the same function and args twice.  So I think what we'd need is to pass in the function generator and the args to the generator, so it can generate an ID unique to the args.

so something like

```go
// DepFunc represents a function that mg.Deps can run that has its own
// way of figuring out what its unique ID should be to avoid multiple runs.
type DepFunc interface {
   MageDepID() string
   Func interface{}
}

// F calls fn with args and returns a function that can be passed to mg.Deps.
// F will generate a unique ID from the function and args so that if you call
// F with the same function and args multiple times, Deps will only run that 
// function once.
func F(fn interface{}, args ...interface{}) DepFunc {
```

And then I just have to figure out how to hash the args so that it produces a consistent ID, which I can use with the same function name I currently use.  Bam, done.

**Comment by 5nord** [comment]
The DepFunc interface wouldn't use sync.Once?

**Comment by natefinch** [comment]
It would because it would get passed to mg.Deps.
mg.Deps would be modified so that if something satisfies DepFunc, it would use the id that it returns in the map of functions, and call its Func value via sync.Once.

**Comment by DavidGamba** [comment]
In my mage like build tool, I only automatically apply a mutex for functions that are not closures:

```
// RunTask - Allows to run a task inside a mutex lock so that in can only run one at a time.
// The task is expected to be idempotent.
// The mutex is not applied to closures, for closures use TaskMutex.
func RunTask(m *SharedMutex, fn getoptions.CommandFn) getoptions.CommandFn {
	fnName := runtime.FuncForPC(reflect.ValueOf(fn).Pointer()).Name()
	return func(ctx context.Context, opt *getoptions.GetOpt, args []string) error {
		if !strings.HasSuffix(fnName, "func1") {
			m.Lock(fnName)
			defer m.Unlock(fnName)
		}
		Logger.Printf("Running Task: %s\n", fnName)
		return fn(ctx, opt, args)
	}
}
```

Then, on the functions that generate closures I use a TaskMutex call with the ID directly:

```
// TaskMutex - Given an identifier for the closure, it ensures that only one version of the closure with the given ID is running at a time.
func TaskMutex(id string) {
	pc := make([]uintptr, 15)
	n := runtime.Callers(2, pc)
	frames := runtime.CallersFrames(pc[:n])
	frame, _ := frames.Next()
	fnName := frame.Function
	Mutex.Lock(fmt.Sprintf("%s-%s", fnName, id))
	defer Mutex.Unlock(fmt.Sprintf("%s-%s", fnName, id))
	Logger.Printf("Running Task: %s\n", fmt.Sprintf("%s-%s", fnName, id))
}
```

For example:

```
// ServiceApply - Runs Terraform apply on the given service.
// It depends on the service plan plus any given explicit dependencies.
func (srv *Service) ServiceApply(dir string, depends ...getoptions.CommandFn) getoptions.CommandFn {
	return func(ctx context.Context, opt *getoptions.GetOpt, args []string) error {
		builddeps.TaskMutex(dir)

		err := builddeps.DependsOn(ctx, opt, args, srv.ServicePlan(dir, depends...))
		if err != nil {
			return err
		}

		name := filepath.Base(dir)
		logger.Printf("Apply: %s\n", name)
		return buildterraform.TerraformApplyDir(srv.DryRun, dir)
	}
}
```

Mage could use that approach to avoid the verbosity of having to implement a method to generate an ID.

**Comment by natefinch** [comment]
this now exists in v1.11
