### ISSUE TITLE
Build C++

### ISSUE THREAD

**Issue by tim-lebedkov** [magefile/mage#315]
is there a way to build C++ projects?

I would need something like this:

: foreach src/*.cpp src/*.c build/gensrc/*.cpp | build/gensrc/*h |> c++ $(CFLAGS) -c %f -o %o |> build/obj/%B.obj

**Comment by natefinch** [comment]
If you can run it as command line, you can run it in Mage. I don't specifically know that syntax, but everything really just ends up being a command that gets run with arguments and inputs, which go can definitely do. 

A shell command is basically always going to be more compact than the equivalent go code, but the error handling will be a lot clearer in the go code, and you won't have people asking stuff like "what does `|>` do?" 

Note that Mage's `sh` package is *not* an actual shell (despite the misleading name - sorry), so you can't just copy a line of shell script into it and have it execute. You'll have to understand what that shell script is actually doing and replicate it in Go.

However, if someone has made a go library that will do that for you, you can just call that library (I don't know if such a library exists).

**Comment by tim-lebedkov** [comment]
As far as I can see you can have targets in Mage, but you cannot have dependencies between files like
a.cpp ==> a.o ==> a.exe
Or am I missing something?

**Comment by natefinch** [comment]
Check out the `target` library and see if that will serve your purpose?
https://pkg.go.dev/github.com/magefile/mage/target

Basically you'd use it like this:
```go
func Build() error {
    // first argument is the target (what would get built), all further args are what it depends on.
    // If any of the dependencies are newer than the target, or if the target doesn't exist,
    // this will return true. All the args will expand environment variables like $FOO or ${Foo}
    // before doing the check.
    outOfDate, err := target.Path("a.exe", "a.o", "a.cpp")
    if err != nil {
        return err
    }
    if !outOfDate {
        // no need to do anything
        return nil 
    }
    // do your build here
}
```

**Comment by tim-lebedkov** [comment]
This is something, but not enough. The dependencies in a C++ project build a big DAG that should be topologically sorted executing all the edges in parallel.

Feel free to close this issue.

**Comment by natefinch** [comment]
Yeah, sorry, that's the best I can do.  I know building C++ is very complicated.  Surely there's another system that has all these rules and features baked in?  Mage is basically just a script with little knowledge of outside systems.

**Comment by DavidGamba** [comment]
@tim-lebedkov I would catalogue Mage as a composable build system more than an out of the box build system the way you intend.

https://please.build/ is a neat Go core alternative if you need the out of the box experience, though the actual language you work with is like a python derivative. Along the same lines Bazel is very popular.
Those work but they are very restrictive, Mage is very flexible and allows you to use the bits and pieces you need.

As far a Go based build systems that build a DAG I myself built one here: 
https://github.com/DavidGamba/go-getoptions/tree/master/dag
But even with that, it is still only the one piece and as @natefinch suggested, I still use the `target` package with it.

**Comment by tim-lebedkov** [comment]
@DavidGamba thank you.
