### ISSUE TITLE
feature: modtime versus docker image age?

### ISSUE THREAD

**Issue by flowchartsman** [magefile/mage#317]
Working on a project now that has a series of services located under `cmd`. Was thinking it might be nice to have a feature to compare the age of any of the files in a given service's subdirectory to the age of the docker image in which they reside. If this would be useful, I'd be happy to code it up.

**Comment by flowchartsman** [comment]
With experimentation, this hasn't been as useful as I'd thought. Closing issue.

**Comment by natefinch** [comment]
FYI you can maybe do this with https://pkg.go.dev/github.com/magefile/mage/target#Dir ?
