### ISSUE TITLE
target package: early exit and time comparisons

### ISSUE THREAD

**Issue by jasonmf** [magefile/mage#323]
Currently, the `target` package does some unnecessary filesystem inspection. It will recurse a directory or inspect a set of source files to collect the newest timestamp then compare that timestamp to a target to see if any of the source timestamps is newer than the target. The logic should be reworked to recurse/inspect, comparing against the target, and stop as soon as a newer source is found.

It would also be useful if the `Dir`, `Glob`, and `Path` functions supported supplying a timestamp as the target, rather than a file path. This would allow for comparison against arbitrary targets like container images using those functions. The existing three functions could then discover the target timestamp for comparison and just wrap functions that take a target timestamp.

PR inbound

**Comment by AgentZombie** [comment]
Created https://github.com/magefile/mage/pull/324

**Comment by natefinch** [comment]
Fixed! Thank you!
