### ISSUE TITLE
magefile.org index page seems missing

### ISSUE THREAD

**Issue by 0xBADDCAFE** [magefile/mage#331]
`site` directory has `content/index.md` , but right pane of index, https://magefile.org doesn't show it.

By the way, logo image in left pane is cutted off. ("e" of Mage) How about using image in README.md instead?

**Comment by natefinch** [comment]
Thank you, the page is fixed now.  Netlify has some weird bug where the homepage doesn't get generated some of the time, but if I rerun the exact same deploy, it works.

Can you screen shot the problem with the logo for me? What resolution / browser are you looking at?

**Comment by 0xBADDCAFE** [comment]
Thanks to fix very soon.

> Can you screen shot the problem with the logo for me? What resolution / browser are you looking at?

I noticed that this causes only Vivaldi browser, mixed monitor resolution. Google Chrome shows it correctly.

```
Vivaldi | 3.5.2115.81 (Stable channel) (64-bit)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36
```

Monitor 1, 2: 4K (150% OS scaling)
Monitor 3: FullHD (100% OS scaling)
Each monitor shows lacked image.

![image](https://user-images.githubusercontent.com/599164/103915344-6c3a6f80-514e-11eb-99c4-845e754191f7.png)

**Comment by 0xBADDCAFE** [comment]
I think that this SVG problem is not to mage project. Sorry to late to close.
