### ISSUE TITLE
Improve error reporting on mg.Deps() usage errors

### ISSUE THREAD

**Issue by flowchartsman** [magefile/mage#332]
Given the following magefile:

```go
// +build mage

package main

import (
        "github.com/magefile/mage/mg"
        "github.com/magefile/mage/sh"
)

func Echo() error {
        return sh.RunV("echo", "hello")
}

func EchoDep() error {
        mg.Deps(mg.F(Echo()))
        return nil
}
```

```
$ mage echo
hello

$ mage echoDep
hello
Error: runtime error: invalid memory address or nil pointer dereference
```

**Comment by flowchartsman** [comment]
I'm a moron. That should be
```go
mg.Deps(mg.F(Echo))
```

**Comment by natefinch** [comment]
Hmmm, yes, but we should have a better error message for that, since this is likely to be a common mistake. Panicking in that case is bad UX.

**Comment by flowchartsman** [comment]
Agreed.

**Comment by flowchartsman** [comment]
To clarify for anyone who finds this issue: the error was the result was making the call to deps against a function result, not a function reference. The apparent success of the dependee function (`Echo()`) was simply that it was run for evaluation at its call site, rather than mage calling it as part of the normal dependency resolution process.  Then `mg.Deps()` attempted reflection on the value (or lack thereof) as opposed to the function reference itself.
