### ISSUE TITLE
run multiple targets?

### ISSUE THREAD

**Issue by natefinch** [magefile/mage#34]
might be nice to do `mage foo,bar` to run both foo and bar.  However, this may have adverse impacts on other features, so it requires some thought.  Input herre is welcome

**Comment by chilts** [comment]
The other thing to think about is whether you'd like to do anything with dependencies. ie. one target relying on another. Perhaps you'd like to keep it simple and not do this (and ignore this comment) since a `func Foo()` can always just call another `func Bar()` in the code and therefore the tool doesn't need to support this.

In terms of your original description, what adverse impacts are you thinking of? I would have thought just calling `Foo()` and then `Bar()` would be fine, on the assumption we only ever call the next target if the first one is successful (doesn't fail).

On a subjective note, I'd drop the comma and just run it as `mage foo bar`. So far no targets take any parameters ... but perhaps that might change in the future.

**Comment by natefinch** [comment]
Yeah, the comma is there to avoid confusion with args, if we ever allow args for targets.  The adverse impact is mostly on allowing args.  

The dependency thing is an interesting problem.  If we try to run both targets in a single process, either one after the other or in parallel, we may run into one of their cleanup steps screwing with the other one.

For example, if one of your dependencies creates a website folder, and at the end of your target run, you clean up that folder.... if the other target that is running depends on that folder existing, it'll blow up.

So, this is definitely more complicated than it seems, unless we run them in series in separate processes, which is fine, but then you're not gaining anything over `mage foo && mage bar`

**Comment by chilts** [comment]
Am just linking in #24 as background input to this issue too.

**Comment by moorereason** [comment]
Migrating from `make`, I expect to do `mage foo bar` and have the targets `foo` and `bar` run in series.

My 2 cents: mage should allow multiple targets or single targets with support for args -- not both.

My vote is to allow multiple targets.  Args are passed via the env.

**Comment by natefinch** [comment]
I guess if they're run in series, that's not a big deal.  It'll have to re-run any dependencies, though, if that's ok?

**Comment by moorereason** [comment]
> The dependency thing is an interesting problem. If we try to run both targets in a single process, either one after the other or in parallel, we may run into one of their cleanup steps screwing with the other one.
> 
> For example, if one of your dependencies creates a website folder, and at the end of your target run, you clean up that folder.... if the other target that is running depends on that folder existing, it'll blow up.

Doesn't the user need to fix their magefile in this case?

**Comment by natefinch** [comment]
I guess I'm not sure how to  fix that from a user perspective.  How do you fix "I want to cleanup after this target is run if it's the only one running, but if I'm running multiple targets, only clean up after all of them have run"

I mean, I guess we could add a cleanup feature that could push cleanup functions on a stack and run them after all targets are finished, sort of like a super-defer, but it's not possible with the current code.

**Comment by moorereason** [comment]
`mage foo bar clean`

**Comment by natefinch** [comment]
ahh duh

**Comment by natefinch** [comment]
next on my list to do then. For now, erroring on multiple targets (#45) was trivial to code, and will at least prevent people from thinking they're running multiple targets when they're not.
