### ISSUE TITLE
Documentation for target arguments

### ISSUE THREAD

**Issue by bjorndm** [magefile/mage#350]
With #326 , in version 1.11.0 of Mage, we now have arguments for targets, which is very useful. However, they are not documented on the web page yet. It would be great if you could document them more in detail. Thanks!

**Comment by bjorndm** [comment]
Nevermind, it seems like I read over it. I found the documentation.

**Comment by FRosner** [comment]
Where is it? :D

**Comment by natefinch** [comment]
https://magefile.org/targets/#arguments
