### ISSUE TITLE
`Unexpected arguments to command` when using `-compile`

### ISSUE THREAD

**Issue by qdm12** [magefile/mage#353]
I'm trying to build [hugo](https://github.com/gohugoio/hugo) statically which uses `mage`.

I'm using

```sh
mage -compile "./" -goarch=amd64 hugo
```

Which uses the target [`hugo`](https://github.com/gohugoio/hugo/blob/master/magefile.go#L52) which is pretty much a `go build` command.

But I keep on geting the error `Error: unexpected arguments to command: ["hugo"]`

I believe this is a logic bug, or am I doing something wrong?

Note that `mage hugo` works without problem. Thanks!

**Comment by natefinch** [comment]
I'm not entirely sure what you mean by build hugo statically.

`mage -compile` creates a self-contained runnable binary that contains all the logic of your magefiles.
The only argument it takes is what you want to name the resultant binary.

so you'd do something like 

```
$ mage -compile "hugo-builder"
$ hugo-builder hugo
```

The first line creates a static binary, which you then can call with the targets that were defined in your magefile.

-compile is mostly for when you want to build your magefiles in a dev environment and then copy the resulting binary to another server to run without needing go installed on that server.

**Comment by qdm12** [comment]
Ah that makes sense, thanks!

Quick not so relevant question, if I want to pass GOARCH to that go build command defined in that `hugo` target, can I just use `GOARCH=arm64 mage hugo` and the `go build` command would pick it up automagically? Thanks!
