### ISSUE TITLE
Goroutine inside magefile not printing to stdout

### ISSUE THREAD

**Issue by thesobercoder** [magefile/mage#354]
I have a target inside the `magefile.go`. I expected the output printed to stdout, but it's doing nothing. I checked each call individually, they work.

This is the single reason I chose `mage` instead of `make`. This is a critical feature for what I'm trying to build. Please help.

```
func Run() error {
	a:= filepath.Join("cmd", "patha", "a.go")
	b:= filepath.Join("cmd", "pathb", "b.go")

	go sh.RunV("go", "run", a)
	go sh.RunV("go", "run", b)

	return nil
}
```

**Comment by natefinch** [comment]
Ahh, the problem is that your code fires off those two goroutines, and then the Run function exits, and then the process exits. 
If you want the Run function to wait for those goroutines to finish, you'll need to do some coordination using a waitgroup.

```
    wg := &sync.WaitGroup{}
    wg.Add(2)
    go func() {
          sh.RunV("go", "run", a)
          wg.Done()
    }()
    go func() {
         go sh.RunV("go", "run", b)
         wg.Done()
    }()
    wg.Wait()
```

**Comment by thesobercoder** [comment]
@natefinch Thanks, man! This works like a charm. Loving Mage. I feel more comfortable writing go than bash scripts. One quick suggestion is maybe to create an overloaded version of `RunV` which accepts `WaitGroup` as a parameter and calls the `done`. Would remove some boilerplate code for a lot of people trying to do this.
