### ISSUE TITLE
Canonical way of returning the first error from a function containing multiple RunV calls

### ISSUE THREAD

**Issue by thesobercoder** [magefile/mage#355]
What would be the canonical way of returning the first error and exit the `Run` target function?

```go
// I want to return the first error that occured and exit the function
func Run() error {
    sh.RunV(...)
    sh.RunV(...)
    sh.RunV(...)
    return sh.RunV(...)   
}
```

**Comment by ryanking** [comment]
I don't think there is anything built into mage for this, but you could implement as a simple helper–

```go
func firstErr(args ...[]string) error {
	for _, a := range args {
		err := sh.Runv(a[0], a[1..len(a)])
		if err != nil {
			return err
		}
	}
	return nil
}

func Run() error {
    return firstErr([]string{...}, []string{...}, []string{...}, []string{...})
}
```

**Comment by natefinch** [comment]
There's no real good way to do that.  Go makes you write out the error handling.

**Comment by arschles** [comment]
another option is something like [go-multierror](https://pkg.go.dev/github.com/hashicorp/go-multierror). it does something vaguely similar to the helper in https://github.com/magefile/mage/issues/355#issuecomment-897131190
