### ISSUE TITLE
Longform comment leaves leading * in docs when `mage` is run

### ISSUE THREAD

**Issue by michaelm-rsi** [magefile/mage#366]
Given the following comment block.
```
/* 
 * Clean all temp directories.
 */
```
When I run `mage`
Then I should see `  clean          Clean all temp directories.` in the mage target list.

Instead I'm seeing `  clean           * Clean all temp directories.`

I admit this is a very minor issue, but it would be nice to have it fixed.

**Comment by natefinch** [comment]
This is a result of how Go parses function docs. Mage uses the standard go parser and gets the docs from that. I bet if you run go doc on that function, it would look the same. Go just doesn't support that kind of comment in docs.

**Comment by michaelm-rsi** [comment]
So refile this request with the go docs team and mage will inherit.  Will do.
