### ISSUE TITLE
Camel case the commands in listing

### ISSUE THREAD

**Issue by bep** [magefile/mage#37]
I get that this is very subjective, but this is from the Hugo build:

```bash
▶ mage
  check            Run tests and linters
  checkvendor      Verify that vendored packages match git HEAD
  docker           Build hugo Docker container
  fmt              Run gofmt linter
  hugo             Build hugo binary
  hugonogitinfo    Build hugo without git info
  hugorace         Build hugo binary with race detector enabled
  install          Install hugo binary
  lint             Run golint linter
  test             Run tests
  test386          Run tests in 32-bit mode
  testcoverhtml    Generate test coverage report
  testrace         Run tests with race detector
  vendor           Install govendor and sync Hugo's vendored dependencies
  vet              Run go vet linter
```

Which is mostly beautiful. But the all lower-case command names looks "wrong" in my eyes. I would much prefer that it followed the original case of the method, but with a lowercase first letter, so `hugoRace`, `testCoverHTML`etc. I would still expect the all lowercase variant to work.

**Comment by natefinch** [comment]
this is a good point... it's definitely hard to read as-is. I had simply lowercased them to make it more obvious that lowercase works.. but I think this will only be a confusion for a short time for most people.

**Comment by chilts** [comment]
I'd be happy to do this feature.

So the question is, what would call `HugoRace`? All of `hugorace`, `hugoRace`, and `HugoRace`?

What about `huGOraCE`? If so, we're essentially going to be comparing the lowercase func names with the lowercased command so everything above amounts to the same thing.

**Comment by bep** [comment]
@chilts as lowercase currently works fine, I would suggest:

* Present them as camel cased (`hugoRace`)
* Lower-case all commands from input (which makes `hugoRace`, `HUGORace` and `hugorace` all fine).

**Comment by chilts** [comment]
Ah yes, presenting them as camel case sounds good. I think the 'original case with first char lower' makes sense, since then we can do the smallest amount of code that does what we want.

**Comment by natefinch** [comment]
once this lands, I think I'll cut a release.  Good enough for a v1 I think :)

**Comment by bep** [comment]
As to release binaries, I assume you know about https://github.com/goreleaser/goreleaser

And it would be cool if you could convince someone to get it into the Brew Core repo, so one could do `brew install mage` etc.

**Comment by natefinch** [comment]
ahh, yes, getting it into brew would be way cool.  I'll look into how to do that.
I had heard of goreleaser, but didn't realize it was quite as cool as it is. :)
