### ISSUE TITLE
doc: consider altering // mage:import documentation to remove leading space 

### ISSUE THREAD

**Issue by efd6** [magefile/mage#406]
The "mage:import" directive comment looks very much like it falls in the family of [directive comments](https://pkg.go.dev/cmd/compile#hdr-Compiler_Directives) used by the compiler and other tools, for example linters (see golang/go#43776).

However it specifies in the documentation that a leading space should be included. The code specifically [does not require this](https://github.com/magefile/mage/blob/526bf4775130d567de6b18fea8f3791d76c8be2a/parse/parse.go#L463-L465), so I would like to suggest that the documentation be changed to exclude the space.

This would have no backward incompatibility issues due to the current acceptance of the no-space variant, but over time would allow the Go community to converge on a consensus approach to using directive comments.

**Comment by natefinch** [comment]
This is a good point. I think changing the recommendation is probably a good idea.

**Comment by efd6** [comment]
There is also the issue of the move to [bug resistant build tags](https://github.com/golang/go/issues/41184) which should be finalised by 1.18 according to the issue. I will send a PR in two commit, the first handling the original issue and the second adjusting docs for the `//go:build` tags, but leaving all the code alone, I can back out the second commit if you don't want it.
