### ISSUE TITLE
Either fail or support multiple targets

### ISSUE THREAD

**Issue by bep** [magefile/mage#42]
See https://github.com/gohugoio/hugo/pull/3939

Good thing I tested.

So I just replaced `make` with `mage` and got:

```bash
mage hugoRace check
```

Wich does not fail. If you do not support multiple targets you really should exit with error + some error message.

**Comment by natefinch** [comment]
So, the idea is that a target may want to process arguments itself.  Right now you can have a target get os.Args and read off the second argument you give it.

There's a couple issues on this - #24 #34 

See the discussion on #34 especially.

I agree that it is suboptimal as-is.  Maybe an interim solution is to default to disallowing extra args, but have an opt-in variable you can set to say you want to process extra args yourself.

like 
```
var ArgPassthrough = true
```

**Comment by bep** [comment]
>I agree that it is suboptimal as-is. 

That isn't the word I would use. Having people moving from `make` to `mage` and think that their build is "green" when it's not, is everything a build system should not be about.

I think you should move extra args to a `--args` flag or something.

**Comment by natefinch** [comment]
I'll make a PR to have mage fail with multiple args until we can flesh out how to run multiple targets in a sane way.
