### ISSUE TITLE
How to install mage with maven

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [magefile/mage#420]
Hi, I want to use Maven to install mage, and then execute the MAGE - V command. Is it feasible? Is there a demo you can refer to?

**Comment by ladydascalie** [comment]
I think this is a question best asked to the Maven team.
I believe this is addressed in their documentation somewhere, `mage` can likely be called as an external program.

**Comment by natefinch** [comment]
Yeah, I don't know anything about maven. There are steps for how to install mage, if you want to run those steps with maven, that's a maven question.
