### ISSUE TITLE
go run bootstrap.go 

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [magefile/mage#423]
I execute “go run bootstrap” on windows Go report the error in the following picture. What should I do？

env：mage@v1.13.0，go1.17.8 。

<img width="859" alt="image" src="https://user-images.githubusercontent.com/76942485/165721395-ad4e5178-9b91-4eed-914c-333ecc037c1a.png">

**Comment by CloudWise-Lukemiao** [comment]
How should I use it on the window command line? I need an automated script

**Comment by natefinch** [comment]
It expects that you checked out the code from git, but it looks like you didn't somehow? Did you copy the code from somewhere?

**Comment by CloudWise-Lukemiao** [comment]
> It expects that you checked out the code from git, but it looks like you didn't somehow? Did you copy the code from somewhere?

I use the following command to execute it. It's OK on Linux, but not on windows. The "go mod tidy" command is downloaded from GIT. But I don't know what's wrong。

![image](https://user-images.githubusercontent.com/76942485/165749988-865afe79-270a-4444-89a7-ea968a296bf3.png)

<img width="662" alt="image" src="https://user-images.githubusercontent.com/76942485/165751160-0ace1bcf-ad59-4b76-946f-6b0430990a4c.png">

**Comment by CloudWise-Lukemiao** [comment]
Can you give me some advice

**Comment by natefinch** [comment]
Installing from inside the pkg directory from someone else's dependencies is not a normal way to install a go application :)

You don't really have to use the bootstrap script. All it does is set some values to tell you what version of mage you're running. You could run `go install` from that directory and it would work fine... it just wouldn't give you information when you ran `mage -version`

**Comment by CloudWise-Lukemiao** [comment]
The problem has been solved. Thank you. I have a new problem/ Can MAGE - V specify the path to compile
