### ISSUE TITLE
Broken mage

### ISSUE THREAD

**Issue by bep** [magefile/mage#46]
This commit https://github.com/magefile/mage/commit/0c1c4dce2f4e5bf8be787115087a0d00bf2560c6

Seem to have broken Hugo (cannot find any of the targets)

**Comment by moorereason** [comment]
A better title would be "mage can't find target."  Example build:  https://travis-ci.org/gohugoio/hugo/jobs/283721261.  `mage hugoRace` didn't find the `hugoRace` target.

Also, when no target is found, mage should exit with non-zero exit code.

**Comment by natefinch** [comment]
this was fixed in #45.  With a test to prevent it from happening again. My apologies.

**Comment by bep** [comment]
No problem; we should lock into a version of `mage` somehow; probably easier once you get some release binaries.

**Comment by natefinch** [comment]
Yeah, I'm going to release binaries today.  Just waiting to see if any more bugs shake out.
