### ISSUE TITLE
Default target as target listing

### ISSUE THREAD

**Issue by moorereason** [magefile/mage#5]
As seen in [Hugo's Makefile](https://github.com/gohugoio/hugo/blob/d9697e275ecb038958b3dcea2b43e11dcba28fc9/Makefile), I like the default target to show a list of available targets.  Is this possible with mage?

**Comment by natefinch** [comment]
mage -l shows the list of available targets.    Making the default target print help..... doesn't work now, but totally doable.  Probably what I'll do is that if there is no default target, then we'll print help.
