### ISSUE TITLE
Running eval in sh.Run()

### ISSUE THREAD

**Issue by barthr** [magefile/mage#57]
Migrating my personal project to mage currently and I tried to run eval in `sh.Run()`. The program outputted 
```Error: failed to run "eval (docker-machine env cryptotraderbot): exec: "eval": executable file not found in $PATH"```

Is there any way to do this with mage or is it currently not supported ?

Relevant code:

```
if err := sh.Run("eval", "$(docker-machine", "env", "cryptotraderbot)"); err != nil {
     return err
}
```

**Comment by interlock** [comment]
Mage uses `exec.Command` which does not invoke commands with a system shell. (see: https://golang.org/pkg/os/exec/)

You can, however, run bash and eval that statement. Something along these lines should work:
`
if err := sh.Run("bash", "-c", "eval", "$(docker-machine", "env", "cryptotraderbot)"); err != nil {
     return err
}
`

**Comment by natefinch** [comment]
yeah, eval is a bash-ism, not an actual binary you can run (check `which eval` and you'll see it doesn't return anything)

You don't really need to use eval, though... you can just run 
```go
s, err := sh.Output("docker-machine", "env", "cryptotraderbot")
```

And then use s where you would have used the eval'd statement

**Comment by mirogta** [comment]
I've found out this to be useful to solve the problem of running piped commands in magefile

E.g.
```
	args := fmt.Sprintf("-c eval $(docker ps | grep %s | cut -d' ' -f1 | xargs -L1 docker stop)", containerName)
	argslist := strings.Split(args, " ")
	if err := sh.Run("bash", argslist...); err != nil {
		return err
	}
```

However this is a bit convoluted.

@natefinch would there be any point making this more comfortable for end users and support piping commands e.g. sh.Pipe, without using the `bash eval` ? it would help a log with migrating more complex build steps from existing Makefiles.
