### ISSUE TITLE
File Source/Target specifications

### ISSUE THREAD

**Issue by natefinch** [magefile/mage#6]
You should be able to declare that a target produces one or more files from one or more files.   If the source files have been modified more recently than the target files (or if the target files don't exist), then run the target, otherwise skip it, assuming it's done.

**Comment by kortschak** [comment]
If you add this, it would be nice to expose the helpers that do the recentness checking.

**Comment by natefinch** [comment]
Yeah. pretty much everything is just going to be a library, like the dependency resolution. The only real magic is finding and running targets.  We'll see if anything else requires similar magic, but I'm trying to err on the side of plain old go code.

**Comment by kortschak** [comment]
Great. BTW, what is the background to the name of the mg package?

**Comment by natefinch** [comment]
I wanted it to be short, since it's likely going to be used in many magefiles.  Someone suggested just "m", but that's too likely to conflict with variable names.  mf was too reminiscent of a certain curse word, so I came up with mg.  basically just mage with the vowels removed. :)

**Comment by natefinch** [comment]
This has been done for a long time ;)
