### ISSUE TITLE
Quotes in comments cause an error

### ISSUE THREAD

**Issue by joncalhoun** [magefile/mage#66]
Having a magefile like this:

```go
// Creates "something"
func Create() error {
  return nil
}
```

Will result in an error. It looks like the quotes aren't being escaped when I check out the intermediate file. Probably a trivial fix but posting here before doing anything to verify it should be fixed.

**Comment by natefinch** [comment]
ha yep. Thanks, should be trivial to fix.

**Comment by natefinch** [comment]
needs to be wrapped in back ticks and then replace any back ticks in the string with single quotes.
