### ISSUE TITLE
Distribute binaries in archived ("standardized") form

### ISSUE THREAD

**Issue by bep** [magefile/mage#68]
Your release binary distro does not resemble "anything else" ... and I would suggest doing something more standardize so people can use the bash scripts they already set up for similar stuff. Package the binary `mage` (i.e. no need for renaming on extract) in a tar file with the execution permissions set. I suspect most Windows AV scanners will jump at the exe downloads etc. Also, I suspect sha 256 hashes are more common.

I started to update my scripts, and what I thought should be a 5 minute task is now turning into real work.

Goreleaser does this right.

**Comment by bep** [comment]
Note that this isn't a big problem for me: But having to create an advanced make script to install mage sounds ...

**Comment by natefinch** [comment]
fixed with https://github.com/magefile/mage/pull/70
