### ISSUE TITLE
Getting random crashes on CircleCI

### ISSUE THREAD

**Issue by bep** [magefile/mage#72]
I've had several issues, so I'm not sure what's what anymore, but I thought I should raise this issue to get a complete picture.

This is with the latest `go get` mage, but I saw this also with the 1.0 version. It does not happen all the time, so may be a memory thing ... But I have never seen this with `make` doing the exact same thing.

```bash
#!/bin/bash -eo pipefail
git clone git@github.com:gohugoio/hugoDocs.git
cd hugo
mage vendor
mage check
Cloning into 'hugoDocs'...
remote: Counting objects: 42080, done.        
remote: Compressing objects: 100% (143/143), done.        
remote: Total 42080 (delta 115), reused 113 (delta 62), pack-reused 41873        
Receiving objects: 100% (42080/42080), 82.94 MiB | 57.03 MiB/s, done.
Resolving deltas: 100% (29294/29294), done.
go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
go build testmain: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
Error: exit status 1
Error: exit status 1
Error: running "govendor test +local" failed with exit code 2
running "govendor test -race +local" failed with exit code 2
Exited with code 2
```

**Comment by bep** [comment]
A quick Google indicating this being a memory thing. I think CircleCI are fairly generous with their memory quota, so that must mean that the `check` target above is too heavy. It contains multiple targets, and I guess each should be run in each own process?

**Comment by natefinch** [comment]
So, compiling is very memory intensive, especially for large applications. Hugo's Check target is running two compilations at the same time - 386 and race.  My guess is that make was running these serially, and that's the difference.

The easiest fix is to simply move either Test386 or TestRace to a separate mg.Deps call.

e.g.
```go
// Run tests and linters
func Check() {
	mg.Deps(Test386, Fmt, Vet)
	// don't run two tests in parallel, they saturate the CPUs anyway, and running two
	// causes memory issues in CI.
	mg.Deps(TestRace)
}
```

The more complicated fix would be to add an option to the CLI to run dependencies serially (i.e. left to right), which is probably a good thing to have, but that's a more complicated fix.

**Comment by bep** [comment]
OK; I will test that ... some other day. I'll close this; I did not know how this worked.

**Comment by natefinch** [comment]
No worries... I did the conversion and I probably should have realized that running two tests in parallel would be a bad idea :)
