### ISSUE TITLE
Proposal: Add sequential deps helper

### ISSUE THREAD

**Issue by moorereason** [magefile/mage#75]
I'd like to see a helper function in `mg` that could run deps sequentially without parallelism.  Some of the deps in Hugo are memory intensive, and I'd like to just run them sequentially.

We can already do this now with multiple `if err := A(); err != nil {}` blocks (or create my own helper function), but a helper function in `mg` would be convenient.

**Comment by interlock** [comment]
Something like `mg.SerialDeps(PreProcess, Process, PostProcess)`?

**Comment by moorereason** [comment]
Yes

**Comment by natefinch** [comment]
This and/or a CLI flag to make deps run serially `mage -serial check` .
