### ISSUE TITLE
The mage released binary isn't self contained

### ISSUE THREAD

**Issue by bep** [magefile/mage#79]
```bash
Resolving deltas: 100% (29367/29367), done.
Error: failed to check types in directory: magefile.go:14:2: could not import github.com/magefile/mage/mg (cannot find package "github.com/magefile/mage/mg" in any of:
	/go/src/github.com/gohugoio/hugo/vendor/github.com/magefile/mage/mg (vendor tree)
	/usr/local/go/src/github.com/magefile/mage/mg (from $GOROOT)
	/go/src/github.com/magefile/mage/mg (from $GOPATH))
Exited with code 1
```

And while I do understand the error above and know the workaround for it, I did expect this to just work without any "go getting". I guess the released binary is just for bootstrapping and not really something one can use for added stability?

Having it in my vendor file would not work either (chicken and egg).

**Comment by natefinch** [comment]
I see what you mean about chicken and egg with downloading deps used by your magefile itself. 

There's a couple possibilities here. One is to have mage dump its own libraries into the vendor directory when it runs.  Then you'd at least be guaranteed to have those and the stdlib.  That doesn't help if you want to use other libraries in your magefile, though.

Another option is that we could have mage integrate with dep to run `dep ensure` before it compiles the magefiles, then it would definitely have everything it needs.  That's a lot more heavy weight, but a lot more complete solution.

A final option would be to let you define a bootstrap magefile that gets run first, that you could guarantee only uses the stdlib, to do whatever needs to be done to set up so the rest of your magefiles have the dependencies they need.  That is most flexible, but puts the onus on the user to write the bootstrap, and adds a lot of complexity.

If you have suggestions on other ways to handle this, I'm all ears.

**Comment by natefinch** [comment]
The other option is to check in the dependencies for your magefiles, so they don't need anything after git clone.

**Comment by bep** [comment]
* I think in most cases you would be fine with Mage + Go stdlib. 
* Adding `dep` as a dependency isn't really solving this ... no dependency wanted issue.
* Dumping build-related stuff into the apps /vendor folder does not sound right either. These libraries have nothing to do with the app itself.
.

**Comment by natefinch** [comment]
ok, so we could have mage copy all the magefiles into a temp dir, set up its own vendor file there with it's built-in helpers (github.com/magefile/mage/sh, mg, target), and then it'll work if you're just using mage & stdlib.  That won't work if people start pulling in third party dependencies.  But we may be able to handle that with a config value - specify whether you want mage to create it's own hermetic deps, or use the project's vendor dir.

**Comment by natefinch** [comment]
btw, I wanted to say that I really value your input on this, @bep.  Getting an idea of what users really want is a huge help.

**Comment by bep** [comment]
>That won't work if people start pulling in third party dependencies.

Sure, but that is how it is with `make`, too, I guess ... If I want `git` I have to somehow handle that on my own.

Not sure if it's possible, but in my head you would set up multiple `GOPATH` and add the "magic mage bundle" in front of that. There is a order here that you kind of have to want when you go for the "download a released binary" variant.

I'm not sure if I agree that this is a "user experience" label, but that doesn't matter. Having a release binary is mostly about knowing what you get (versioning); right now `1.0.2` isn't really that in the practical sense of it.

**Comment by natefinch** [comment]
That's fair.  I marked it as UX because there's a way you have to do things right now (check in a vendor dir) that is obviously suboptimal.

**Comment by bep** [comment]
Thinking about it, maybe the pragmatic choice is to do `go get gopkg.in/magefile/mage.v1` ... Not optimal. It would be cool if there were some added security to the above (sha validation of sorts).

**Comment by natefinch** [comment]
That's probably ok for now, but mage could certainly drop its own files into the first entry in gopath easily enough, to avoid any worry about where the code is coming from.

**Comment by moorereason** [comment]
The fundamental issue is that the upstream mage API deviated from what Hugo has vendored, which breaks our magefile.

Two work-arounds:

1. Use the [Zero Install Option](https://magefile.org/zeroinstall/).
```
go run mage.go -v hugo
```

2. Install vendored mage.  This seems like the simplest solution for Hugo right now.
```
go install ./vendor/github.com/magefile/mage/...
mage -v hugo
```

The mage API will need to become extremely stable if you want to dethrone `make`.

**Comment by natefinch** [comment]
@moorereason It's fixable, a few different ways.  I've been stalling, because I wanted more time to think on it and more time to see what other problems crop up.  For example, this conflict between `go install`ing mage from master and having a different version's libraries vendored is an interesting problem that I wouldn't have thought of before this latest problem.

My apologies for the problems this is causing, please know that I understand it is a serious problem, and it's my highest priority to fix... I just want to make sure that I fix it the right way, so more problems don't crop up.

**Comment by natefinch** [comment]
Thought I just had.  What about a precompile declaration that could let you run whatever commands you want before mage compiles itself?

Like go get dep, dep ensure?

**Comment by bep** [comment]
Just a footnote here ... I kind of didn't want to add `mage` as a vendored dependency, but `dep` seems to insist ...

**Comment by natefinch** [comment]
Although I think it's wise to vendor the deps of mage, I do understand your inclination. I could have mage look for magefiles under a .magefile subdirectory by default. Then I think dep would ignore those.

**Comment by Dr-Terrible** [comment]
What about bundling mage's deps¹ inside its binary (using something like go-bindata or packr),  and then run a self-contained GOPATH environment to just compile the magefiles (something in the style of [Gb](http://github.com/constabulary/gb) )?

**Comment by natefinch** [comment]
Coming back to this... I think vgo in the go tool and go modules will solve the problem of getting a vendoring tool before you get mage. 
 
As for not vendoring dependencies of your magefile, I actually think you definitely should.  Making sure your tooling for any specific release is consistent is actually really important.   I'll be looking into how vgo works with mage in the coming days... hopefully it'll Just Work, given that mage really just calls go build after generating a little code.

**Comment by bep** [comment]
I have done some testing in the process of getting Hugo onto Go modules. And even after deleting `$GOPATH/bin/mage` and then doing the below:

```bash
go/gohugoio/hugo  gomod ✗                                                                                 1h51m ⚑
▶ go get -u -v github.com/magefile/mage
go: finding github.com/magefile/mage v1.0.2+incompatible

go/gohugoio/hugo  gomod ✗                                                                                 1h51m ⚑
▶ mage -version
Mage Build Tool v2
Build Date: <not set>
Commit: <not set>
```

I have explicitly set an old version in go.mod, but still get the v2 version installed (I assume the build string reports correctly). I find this a little confusing. Not sure what the "incompatible" string means. I guess I will have to read some docs.

**Comment by natefinch** [comment]
Maybe it's not putting the binary where you expect, so you're actually
running different binary.

If you build without using the magefile, it won't set the version at all.

**Comment by bep** [comment]
>Maybe it's not putting the binary where you expect, so you're actually
running different binary.

Sure. But I deleted the mage binary before I ran the above. So I know that **that command** produced that binary.

**Comment by natefinch** [comment]
I'm saying that you probably have another mage binary hanging around
somewhere. It wouldn't say v2 unless you had built it with ldflags.

**Comment by bep** [comment]
@natefinch you are probably right.

But I have been fiddling with this the last few days, now latest with the Appveyor Hugo build. And I suspect this is a limitation with `go get` and Go Modules. I need a Mage binary, but if I build without a `GOPATH` and do:

```
go get github.com/magefile/mage
go: downloading github.com/magefile/mage v2.2.0+incompatible
mage hugoRace
Error: failed to check types in directory: magefile.go:17:2: could not import github.com/magefile/mage/mg (type-checking package "github.com/magefile/mage/mg" failed (C:\GOPATH\pkg\mod\github.com\magefile\mage@v2.2.0+incompatible\mg\deps.go:13:2: could not import github.com/magefile/mage/types (cannot find package "github.com/magefile/mage/types" in any of:
	C:\go\src\github.com\magefile\mage\types (from $GOROOT)
	C:\GOPATH\src\github.com\magefile\mage\types (from $GOPATH))))
```

If I add a `GOPATH`, it starts working ... But then I'm not really sure what `mage` version I'm using.

**Comment by natefinch** [comment]
btw, I was wrong... I default the version to v2 when there's no branch info, because at least that part I know will be true.  But it does make it sorta confusing when it's not built using ldflags.

I'll be putting a go.mod in mage ASAP.  So that these things work as expected.

**Comment by natefinch** [comment]
OK, I released 2.3.0 which includes better 1.11 support and a go.mod file. I am hopeful this will fix everything.

**Comment by bep** [comment]
I suspect what I get now is partly a bug in Go Modules (at least it confuses me big time).

* See https://github.com/gohugoio/hugo/pull/5154 -- it updates to the pseudo version 	github.com/magefile/mage v0.0.0-20180902034105-68374889480d -- which I suspect is because of your "non standard" version tag `2.3.0` (vs `v2.3.0` -- I don't find this documented anywhere).
* However, building with this new version still seems to resolve to `v.2.2.0`... https://ci.appveyor.com/project/bep/hugo-i6m5hfpeb1vq3wl/build/1.0.3046

**Comment by ctd1500** [comment]
The documentation was there in the spec for vgo, and now on the [Go wiki](https://github.com/golang/go/wiki/Modules#version-selection)
`Modules must be semantically versioned in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v3.0.1. The leading v is required. If using Git, tag released commits with their versions.`

**Comment by natefinch** [comment]
Gah, that's so annoying.

I just pushed a tag with the v in it. This is going to hit s lot of people
I bet.

**Comment by bep** [comment]
I'm not having any luck getting to `v2.3.0` -- seems `go mod` is confused ...

**Comment by natefinch** [comment]
Gah, I'll look at this more tonight... Modules are not as straight forward as I'd like.

**Comment by natefinch** [comment]
Ahh, I think this is because if you have a v2 or higher, then the import needs /v2 at the end.. including the one in the go.mod file.  Dammit.  I really don't want v2 in the import path..... maybe I'll be a horrible maintainer and switch to v1.x just to avoid it

**Comment by natefinch** [comment]
I did some horribleness and made v1.2.4 the current master.  That seems to fix go modules so they do the right thing.  Please forgive me for screwing up previous tags.

**Comment by bep** [comment]
Reopen this, as I had a "YAML issue" with my Travis config that made me think it was "green".

```bash

Error parsing magefiles: failed to check types in directory: magefile.go:18:2: could not import github.com/magefile/mage/mg (cannot find package "github.com/magefile/mage/mg" in any of:
	/Users/travis/.gimme/versions/go1.11.darwin.amd64/src/github.com/magefile/mage/mg (from $GOROOT)
	/Users/travis/gopath/src/github.com/magefile/mage/mg (from $GOPATH))
```

I can add that I mysteriously got the below error:

```bash
go: downloading github.com/magefile/mage v1.2.4
go: verifying github.com/magefile/mage@v1.2.4: checksum mismatch
	downloaded: h1:Olsqw6CIOK4dYqrCAZ2tEiwdg4jx0g1wltVvuOuFhPE=
	go.sum:     h1:2QnmtjngYyEG7hFmpnWXcqNg6dYRerYkrltrIcYu1o0=
```

Which does indicate some odd stuff going on.

**Comment by bep** [comment]
I can add that I get the "could not import" error when using the latest commit, too.

**Comment by bep** [comment]
... but it works locally, which suggests that this does not work with `env GO111MODULE=on` inside `GOPATH`.

**Comment by bep** [comment]
OK, so https://github.com/bep/hugo/commit/cb81dbd41828f6dc4d65a08aff64392e5e8b1935 makes it build. But I'm not sure what version of Mage I'm actually running here ... Would it be possible to add a commit to master that fixed some spelling in a help text or something?

**Comment by natefinch** [comment]
If you run mage version with the newest master without running mage
install, it'll say version unknown instead of v2.

**Comment by bep** [comment]
Thanks. Yes, then it works:

```bash
go get -u -v github.com/magefile/mage@68374889480d95d7e4b6626a1843e7cb559ac3e4
go: finding github.com/magefile/mage 68374889480d95d7e4b6626a1843e7cb559ac3e4
go: downloading github.com/magefile/mage v1.0.3-0.20180902034105-68374889480d
github.com/magefile/mage/types
github.com/magefile/mage/build-1.11
github.com/magefile/mage/build-1.10
github.com/magefile/mage/mg
github.com/magefile/mage/parse
github.com/magefile/mage/sh
github.com/magefile/mage/mage
github.com/magefile/mage

go/gohugoio/hugo  fix-travis ✗                                                                                                                       4h13m ⚑
▶ mage -version
Mage Build Tool v2
Build Date: <not set>
Commit: <not set>
```

Lessons learned:

* Go still needs a `GOPATH` even if you use Go Modules
* To install the `go.mod` version of the Mage binary, this need to be done outside of `GOPATH`. Doing ` env GO111MODULE=on go get github.com/magefile/mage` does not work.
