### ISSUE TITLE
mage -init

### ISSUE THREAD

**Issue by natefinch** [magefile/mage#8]
create a new flag -init that creates a new default magefile.

**Comment by interlock** [comment]
Interesting project, how can I help with this feature?

My assumption is to create a `mage.go` (or similar) file in current folder with the required `// +build mage` and perhaps a starting point for `Build()` and `Install()` ?

- [ ] creates default mage file
- [ ] accepts override for that file name
- [ ] template generated for Build and Install
- [ ] commented template (perhaps overly verbose as a default?)

**Comment by natefinch** [comment]
Exactly yes to everything :)

For now, the generated file will be pretty simple.  But as new features get added, the generated file and comments should get updated and help give users a head start on writing a magefile, so they don't start with just an empty text editor.

**Comment by interlock** [comment]
Nice! I'll see what I can whip up into a PR with tests tonight.
