### ISSUE TITLE
Pass in parameters?

### ISSUE THREAD

**Issue by bobhenkel** [magefile/mage#92]
Is there no way to pass in variables to a target?  I see the docs state a function with no args.

Something like:
```
mage buildDocker -imageName myimage -tag 1.0
```

I'm really new to golang so maybe there's some other way to do this without mage needing to care, but seems like it would be hard to know what parameters a target needs without digging into the code implementation vs just looking a function definition.

**Comment by natefinch** [comment]
Right now the answer is to use environment variables.  There's a couple issues open about how to handle this. But for now you'll have to rely on environment variables.  Check out os.Getenv(), it's pretty straightforward.

**Comment by natefinch** [comment]
See #24
